CREATE procedure [dbo].[USP_AddUserStory]
(
@UserStoryId UNIQUEIDENTIFIER = NULL,
  @GoalId UNIQUEIDENTIFIER = NULL,
  @UserStoryName NVARCHAR(800) = NULL, 
  @EstimatedTime DECIMAL(18,2) = NULL,
  @DeadLineDate DATETIMEOFFSET = NULL,
  @OwnerUserId UNIQUEIDENTIFIER = NULL ,
  @TestSuiteSectionId UNIQUEIDENTIFIER = NULL ,
  @TestCaseId UNIQUEIDENTIFIER = NULL ,
  @DependencyUserId UNIQUEIDENTIFIER = NULL,
  @Order INT = NULL,
  @UserStoryStatusId UNIQUEIDENTIFIER = NULL,
  @IsArchived BIT = NULL,
  @ArchivedDateTime DATETIME = NULL,
  @BugPriorityId UNIQUEIDENTIFIER = NULL,
  @UserStoryTypeId UNIQUEIDENTIFIER = NULL,
  @ParkedDateTime DATETIME = NULL,
  @ProjectFeatureId UNIQUEIDENTIFIER = NULL,
  @BugCausedUserId UNIQUEIDENTIFIER = NULL,
  @UserStoryPriorityId UNIQUEIDENTIFIER = NULL,
  @ReviewerUserId UNIQUEIDENTIFIER = NULL,
  @ParentUserStoryId UNIQUEIDENTIFIER = NULL,
  @OperationsPerformedBy UNIQUEIDENTIFIER ,
  @Description NVARCHAR(MAX) = NULL,
  @TimeStamp TIMESTAMP = NULL,
  @IsForQa BIT = NULL,
  @VersionName NVARCHAR(250) = NULL,
  @Tags NVARCHAR(MAX) = NULL
  )
as
begin
  
  INSERT INTO [dbo].[UserStory](
                                           [Id],
                                           [GoalId],
                                           [UserStoryName],
                                           [EstimatedTime],
                                           [DeadLineDate],
                                           [OwnerUserId],
										   [TestSuiteSectionId],
										   [TestCaseId],
                                           [DependencyUserId],
                                           [Order],
                                           [UserStoryStatusId],
                                           [ActualDeadLineDate],
                                           [ArchivedDateTime],
                                           [BugPriorityId],
                                           [UserStoryTypeId],
                                           [ParkedDateTime],
                                           [ProjectFeatureId],
                                           [UserStoryPriorityId],
                                           [ReviewerUserId],
                                           [ParentUserStoryId],
                                           [CreatedDateTime],
                                           [CreatedByUserId],
										   UserStoryUniqueName,
										   [InActiveDateTime],
										   [Description],
										   [IsForQa],
										   [VersionName],
										   [Tag]
                                           )
                                    SELECT @UserStoryId,
                                           @GoalId,
                                           @UserStoryName,
                                           CASE WHEN @EstimatedTime = 0 THEN NULL ELSE @EstimatedTime END,
                                           @DeadLineDate,
                                           @OwnerUserId,
										   @TestSuiteSectionId,
										   @TestCaseId,
                                           @DependencyUserId,
                                           CASE WHEN @UserStoryId IS NULL THEN 5 + 1 ELSE @Order END,
                                           @UserStoryStatusId,
                                           ISNULL(GETDATE(),@DeadLineDate),
                                           CASE WHEN @IsArchived = 1 THEN GETDATE() ELSE NULL END,
                                           @BugPriorityId,
                                           @UserStoryTypeId,
                                           @ParkedDateTime,
                                           @ProjectFeatureId,
                                           @UserStoryPriorityId,
                                           @ReviewerUserId,
                                           @ParentUserStoryId,
                                           GETDATE(),
                                           @OperationsPerformedBy,
										   @UserStoryName,
                                           CASE WHEN @IsArchived = 1 THEN GETDATE() ELSE NULL END,
										   @Description,
										   @IsForQa,
										   @VersionName,
										   @Tags

end