CREATE PROCEDURE [dbo].[Marker68]
(
    @CompanyId UNIQUEIDENTIFIER,
    @UserId UNIQUEIDENTIFIER,
    @RoleId UNIQUEIDENTIFIER
)
AS 
BEGIN 
SET NOCOUNT ON

    MERGE INTO [dbo].RateTagFor AS Target 
    USING (VALUES 
    		(NEWID(), @CompanyId, N'Regular day',0, CAST(N'2018-08-13 08:22:39.083' AS DateTime), @UserId),
    		(NEWID(), @CompanyId, N'Bank Holiday',0, CAST(N'2018-08-13 08:22:39.083' AS DateTime), @UserId),
    		(NEWID(), @CompanyId, N'Early',1, CAST(N'2018-08-13 08:22:39.083' AS DateTime), @UserId),
    		(NEWID(), @CompanyId, N'Overtime',1, CAST(N'2018-08-13 08:22:39.083' AS DateTime), @UserId),
    		(NEWID(), @CompanyId, N'Paid break',1, CAST(N'2018-08-13 08:22:39.083' AS DateTime), @UserId)
    )
    AS Source ([Id],[CompanyId],[RateTagForName],IsAllowance,[CreatedDateTime],[CreatedByUserId]) 
    ON Target.Id = Source.Id  
    WHEN MATCHED THEN 
    UPDATE SET CompanyId = Source.CompanyId,
    	       [RateTagForName] = Source.[RateTagForName],
    		   [IsAllowance] = Source.[IsAllowance],
    	       [CreatedDateTime] = Source.[CreatedDateTime],
    		   [CreatedByUserId] = Source.[CreatedByUserId]
    WHEN NOT MATCHED BY TARGET THEN 
    INSERT ([Id],[CompanyId],[RateTagForName],IsAllowance,[CreatedDateTime],[CreatedByUserId]) 
    VALUES ([Id],[CompanyId],[RateTagForName],IsAllowance,[CreatedDateTime],[CreatedByUserId]);
    
     --INSERT INTO [CustomStoredProcWidget](Id,CustomWidgetId,ProcName,CompanyId,CreatedByUserId,CreatedDateTime,Inputs,Outputs)
    MERGE INTO [dbo].[CustomStoredProcWidget] AS Target 
    USING ( VALUES 
            (NEWID(),(SELECT Id FROM CustomWidgets WHERE CompanyId = @CompanyId AND InActiveDateTime IS NULL AND CustomWidgetName = 'BirthDays Report'),'USP_BirthDaysReport',@CompanyId,@UserId,GETDATE(),'[{"ParameterName":"@OperationsPerformedBy","DataType":"uniqueidentifier","InputData":"@OperationsPerformedBy"},{"ParameterName":"@DateFrom","DataType":"datetime","InputData":"@DateFrom"},{"ParameterName":"@DateTo","DataType":"datetime","InputData":"@DateTo"},{"ParameterName":"@ColumnString","DataType":"nvarchar","InputData":null},{"ParameterName":"@EntityId","DataType":"uniqueidentifier","InputData":"@EntityId"}]',NULL)
            ,(NEWID(),(SELECT Id FROM CustomWidgets WHERE CompanyId = @CompanyId AND InActiveDateTime IS NULL AND CustomWidgetName = 'Day Wise Leave Transaction Report'),'USP_DayWiseLeaveTransactionReport',@CompanyId,@UserId,GETDATE(),'[{"ParameterName":"@OperationsPerformedBy","DataType":"uniqueidentifier","InputData":"@OperationsPerformedBy"},{"ParameterName":"@ColumnString","DataType":"nvarchar","InputData":null},{"ParameterName":"@EntityId","DataType":"uniqueidentifier","InputData":"@EntityId"},{"ParameterName":"@IsActiveEmployeesOnly","DataType":"BIT","InputData":"@IsActiveEmployeesOnly"},{"ParameterName":"@Date","DataType":"DATETIME","InputData":"@Date"}]',NULL)
            ,(NEWID(),(SELECT Id FROM CustomWidgets WHERE CompanyId = @CompanyId AND InActiveDateTime IS NULL AND CustomWidgetName = 'Hold Salary Report'),'USP_HoldSalaryReport',@CompanyId,@UserId,GETDATE(),'[{"ParameterName":"@OperationsPerformedBy","DataType":"uniqueidentifier","InputData":"@OperationsPerformedBy"},{"ParameterName":"@Month","DataType":"datetime","InputData":"@Month"},{"ParameterName":"@ColumnString","DataType":"nvarchar","InputData":null},{"ParameterName":"@EntityId","DataType":"uniqueidentifier","InputData":"@EntityId"}]',NULL)
            ,(NEWID(),(SELECT Id FROM CustomWidgets WHERE CompanyId = @CompanyId AND InActiveDateTime IS NULL AND CustomWidgetName = 'Joining Anniversary Report'),'USP_JoiningAnniversaryReport',@CompanyId,@UserId,GETDATE(),'[{"ParameterName":"@OperationsPerformedBy","DataType":"uniqueidentifier","InputData":"@OperationsPerformedBy"},{"ParameterName":"@DateFrom","DataType":"datetime","InputData":"@DateFrom"},{"ParameterName":"@DateTo","DataType":"datetime","InputData":"@DateTo"},{"ParameterName":"@ColumnString","DataType":"nvarchar","InputData":null},{"ParameterName":"@EntityId","DataType":"uniqueidentifier","InputData":"@EntityId"}]',NULL)
            ,(NEWID(),(SELECT Id FROM CustomWidgets WHERE CompanyId = @CompanyId AND InActiveDateTime IS NULL AND CustomWidgetName = 'Leave Availed Report'),'USP_LeaveAvailedReport',@CompanyId,@UserId,GETDATE(),'[{"ParameterName":"@OperationsPerformedBy","DataType":"uniqueidentifier","InputData":"@OperationsPerformedBy"},{"ParameterName":"@DateFrom","DataType":"datetime","InputData":"@DateFrom"},{"ParameterName":"@DateTo","DataType":"datetime","InputData":"@DateTo"},{"ParameterName":"@ColumnString","DataType":"nvarchar","InputData":null},{"ParameterName":"@EntityId","DataType":"uniqueidentifier","InputData":"@EntityId"},{"ParameterName":"@IsActiveEmployeesOnly","DataType":"BIT","InputData":"@IsActiveEmployeesOnly"}]',NULL)
            ,(NEWID(),(SELECT Id FROM CustomWidgets WHERE CompanyId = @CompanyId AND InActiveDateTime IS NULL AND CustomWidgetName = 'Leave Backdated Report'),'USP_LeaveBackdatedReport',@CompanyId,@UserId,GETDATE(),'[{"ParameterName":"@OperationsPerformedBy","DataType":"uniqueidentifier","InputData":"@OperationsPerformedBy"},{"ParameterName":"@DateFrom","DataType":"datetime","InputData":"@DateFrom"},{"ParameterName":"@DateTo","DataType":"datetime","InputData":"@DateTo"},{"ParameterName":"@ColumnString","DataType":"nvarchar","InputData":null},{"ParameterName":"@EntityId","DataType":"uniqueidentifier","InputData":"@EntityId"},{"ParameterName":"@IsActiveEmployeesOnly","DataType":"BIT","InputData":"@IsActiveEmployeesOnly"}]',NULL)
       --TODO     
            ,(NEWID(),(SELECT Id FROM CustomWidgets WHERE CompanyId = @CompanyId AND InActiveDateTime IS NULL AND CustomWidgetName = 'Leave Encashment Report'),'USP_LeaveEncashmentReport',@CompanyId,@UserId,GETDATE(),'[{"ParameterName":"@OperationsPerformedBy","DataType":"uniqueidentifier","InputData":"@OperationsPerformedBy"},{"ParameterName":"@DateFrom","DataType":"datetime","InputData":"@DateFrom"},{"ParameterName":"@DateTo","DataType":"datetime","InputData":"@DateTo"},{"ParameterName":"@ColumnString","DataType":"nvarchar","InputData":null},{"ParameterName":"@EntityId","DataType":"uniqueidentifier","InputData":"@EntityId"},{"ParameterName":"@IsActiveEmployeesOnly","DataType":"BIT","InputData":"@IsActiveEmployeesOnly"}]',NULL)
            ,(NEWID(),(SELECT Id FROM CustomWidgets WHERE CompanyId = @CompanyId AND InActiveDateTime IS NULL AND CustomWidgetName = 'Leave Transaction Report'),'USP_LeaveTransactionReport',@CompanyId,@UserId,GETDATE(),'[{"ParameterName":"@OperationsPerformedBy","DataType":"uniqueidentifier","InputData":"@OperationsPerformedBy"},{"ParameterName":"@DateFrom","DataType":"datetime","InputData":"@DateFrom"},{"ParameterName":"@DateTo","DataType":"datetime","InputData":"@DateTo"},{"ParameterName":"@ColumnString","DataType":"nvarchar","InputData":null},{"ParameterName":"@EntityId","DataType":"uniqueidentifier","InputData":"@EntityId"},{"ParameterName":"@IsActiveEmployeesOnly","DataType":"BIT","InputData":"@IsActiveEmployeesOnly"}]',NULL)
            ,(NEWID(),(SELECT Id FROM CustomWidgets WHERE CompanyId = @CompanyId AND InActiveDateTime IS NULL AND CustomWidgetName = 'Marriage Anniversary Report'),'USP_MarriageAnniversaryReport',@CompanyId,@UserId,GETDATE(),'[{"ParameterName":"@OperationsPerformedBy","DataType":"uniqueidentifier","InputData":"@OperationsPerformedBy"},{"ParameterName":"@DateFrom","DataType":"datetime","InputData":"@DateFrom"},{"ParameterName":"@DateTo","DataType":"datetime","InputData":"@DateTo"},{"ParameterName":"@ColumnString","DataType":"nvarchar","InputData":null},{"ParameterName":"@EntityId","DataType":"uniqueidentifier","InputData":"@EntityId"}]',NULL)
            ,(NEWID(),(SELECT Id FROM CustomWidgets WHERE CompanyId = @CompanyId AND InActiveDateTime IS NULL AND CustomWidgetName = 'Quick Salary Report'),'USP_QuickSalaryReport',@CompanyId,@UserId,GETDATE(),'[{"ParameterName":"@OperationsPerformedBy","DataType":"uniqueidentifier","InputData":"@OperationsPerformedBy"},{"ParameterName":"@Month","DataType":"datetime","InputData":"@Month"},{"ParameterName":"@ColumnString","DataType":"nvarchar","InputData":null},{"ParameterName":"@IsActiveEmployeesOnly","DataType":"BIT","InputData":"@IsActiveEmployeesOnly"},{"ParameterName":"@EntityId","DataType":"uniqueidentifier","InputData":"@EntityId"}]',NULL)
            ,(NEWID(),(SELECT Id FROM CustomWidgets WHERE CompanyId = @CompanyId AND InActiveDateTime IS NULL AND CustomWidgetName = 'Negative Leave Balance Report'),'USP_NegativeLeaveBalanceReport',@CompanyId,@UserId,GETDATE(),'[{"ParameterName":"@OperationsPerformedBy","DataType":"uniqueidentifier","InputData":"@OperationsPerformedBy"},{"ParameterName":"@Month","DataType":"datetime","InputData":"@Month"},{"ParameterName":"@ColumnString","DataType":"nvarchar","InputData":null},{"ParameterName":"@EntityId","DataType":"uniqueidentifier","InputData":"@EntityId"},{"ParameterName":"@IsActiveEmployeesOnly","DataType":"BIT","InputData":"@IsActiveEmployeesOnly"}]',NULL)
            ,(NEWID(),(SELECT Id FROM CustomWidgets WHERE CompanyId = @CompanyId AND InActiveDateTime IS NULL AND CustomWidgetName = 'Year Wise Leave Summary Report'),'USP_YearWiseLeaveSummaryReport',@CompanyId,@UserId,GETDATE(),'[{"ParameterName":"@OperationsPerformedBy","DataType":"uniqueidentifier","InputData":"@OperationsPerformedBy"},{"ParameterName":"@Year","DataType":"datetime","InputData":"@Year"},{"ParameterName":"@ColumnString","DataType":"nvarchar","InputData":null},{"ParameterName":"@EntityId","DataType":"uniqueidentifier","InputData":"@EntityId"},{"ParameterName":"@IsActiveEmployeesOnly","DataType":"BIT","InputData":"@IsActiveEmployeesOnly"}]',NULL)
            ,(NEWID(),(SELECT Id FROM CustomWidgets WHERE CompanyId = @CompanyId AND InActiveDateTime IS NULL AND CustomWidgetName = 'Leave Summary Report'),'USP_LeaveSummaryReport',@CompanyId,@UserId,GETDATE(),'[{"ParameterName":"@OperationsPerformedBy","DataType":"uniqueidentifier","InputData":"@OperationsPerformedBy"},{"ParameterName":"@Year","DataType":"datetime","InputData":"@Year"},{"ParameterName":"@ColumnString","DataType":"nvarchar","InputData":null},{"ParameterName":"@EntityId","DataType":"uniqueidentifier","InputData":"@EntityId"},{"ParameterName":"@IsActiveEmployeesOnly","DataType":"BIT","InputData":"@IsActiveEmployeesOnly"},{"ParameterName":"@UserId","DataType":"uniqueidentifier","InputData":"@UserId"}]',NULL)
            ,(NEWID(),(SELECT Id FROM CustomWidgets WHERE CompanyId = @CompanyId AND InActiveDateTime IS NULL AND CustomWidgetName = 'Proof of Investment Declaration Report'),'USP_GetProofofInvestmentDeclaration',@CompanyId,@UserId,GETDATE(),'[{"ParameterName":"@OperationsPerformedBy","DataType":"uniqueidentifier","InputData":"@OperationsPerformedBy"},{"ParameterName":"@UserId","DataType":"uniqueidentifier","InputData":"@UserId"},{"ParameterName":"@EntityId","DataType":"uniqueidentifier","InputData":"@EntityId"},{"ParameterName":"@IsActiveEmployeesOnly","DataType":"BIT","InputData":"@IsActiveEmployeesOnly"},{"ParameterName":"@Year","DataType":"datetime","InputData":"@Year"},{"ParameterName":"@IsFinantialYearBased","DataType":"BIT","InputData":"@IsFinancialYear"}]',NULL)
            ,(NEWID(),(SELECT Id FROM CustomWidgets WHERE CompanyId = @CompanyId AND InActiveDateTime IS NULL AND CustomWidgetName = 'ESI Monthly Summary Report'),'USP_ESIMonthlySummaryReport',@CompanyId,@UserId,GETDATE(),'[{"ParameterName":"@OperationsPerformedBy","DataType":"uniqueidentifier","InputData":"@OperationsPerformedBy"},{"ParameterName":"@Month","DataType":"datetime","InputData":"@Month"},{"ParameterName":"@EntityId","DataType":"uniqueidentifier","InputData":"@EntityId"},{"ParameterName":"@IsActiveEmployeesOnly","DataType":"BIT","InputData":"@IsActiveEmployeesOnly"},{"ParameterName":"@UserId","DataType":"uniqueidentifier","InputData":"@UserId"}]',NULL)
            ,(NEWID(),(SELECT Id FROM CustomWidgets WHERE CompanyId = @CompanyId AND InActiveDateTime IS NULL AND CustomWidgetName = 'PF Monthly Statement'),'USP_PFMonthlyStatement',@CompanyId,@UserId,GETDATE(),'[{"ParameterName":"@OperationsPerformedBy","DataType":"uniqueidentifier","InputData":"@OperationsPerformedBy"},{"ParameterName":"@Month","DataType":"datetime","InputData":"@Month"},{"ParameterName":"@EntityId","DataType":"uniqueidentifier","InputData":"@EntityId"},{"ParameterName":"@IsActiveEmployeesOnly","DataType":"BIT","InputData":"@IsActiveEmployeesOnly"},{"ParameterName":"@UserId","DataType":"uniqueidentifier","InputData":"@UserId"}]',NULL)
            ,(NEWID(),(SELECT Id FROM CustomWidgets WHERE CompanyId = @CompanyId AND InActiveDateTime IS NULL AND CustomWidgetName = 'IT Savings Report'),'USP_GetITSavingsReport',@CompanyId,@UserId,GETDATE(),'[{"ParameterName":"@OperationsPerformedBy","DataType":"uniqueidentifier","InputData":"@OperationsPerformedBy"},{"ParameterName":"@EntityId","DataType":"uniqueidentifier","InputData":"@EntityId"},{"ParameterName":"@IsActiveEmployeesOnly","DataType":"BIT","InputData":"@IsActiveEmployeesOnly"},{"ParameterName":"@UserId","DataType":"uniqueidentifier","InputData":"@UserId"},{"ParameterName":"@Year","DataType":"datetime","InputData":"@Year"},{"ParameterName":"@IsFinantialYearBased","DataType":"BIT","InputData":"@IsFinancialYear"}]',NULL)
            ,(NEWID(),(SELECT Id FROM CustomWidgets WHERE CompanyId = @CompanyId AND InActiveDateTime IS NULL AND CustomWidgetName = 'Income Tax Monthly Statement'),'USP_GetIncomeTaxMonthlyStatement',@CompanyId,@UserId,GETDATE(),'[{"ParameterName":"@OperationsPerformedBy","DataType":"uniqueidentifier","InputData":"@OperationsPerformedBy"},{"ParameterName":"@Month","DataType":"datetime","InputData":"@Month"},{"ParameterName":"@EntityId","DataType":"uniqueidentifier","InputData":"@EntityId"},{"ParameterName":"@IsActiveEmployeesOnly","DataType":"BIT","InputData":"@IsActiveEmployeesOnly"},{"ParameterName":"@UserId","DataType":"uniqueidentifier","InputData":"@UserId"}]',NULL)
    )
    AS Source (Id,CustomWidgetId,ProcName,CompanyId,CreatedByUserId,CreatedDateTime,Inputs,Outputs)
    ON Target.CustomWidgetId = Source.CustomWidgetId AND Target.CompanyId = Source.CompanyId AND Target.ProcName = Source.ProcName
    WHEN MATCHED THEN
    UPDATE SET Inputs = Source.Inputs;

	UPDATE CustomWidgets SET WidgetQuery = 'SELECT [Date],DATEADD(MINUTE,[dbo].[Ufn_GetOffsetInMinutes](''@OperationsPerformedBy''),cast([Avg exit time] as time(0))) [Avg exit time] FROM
	(SELECT FORMAT([Date],''dd-MM-yy'') AS [Date],ISNULL(CAST(AVG(CAST(OutTime AS FLOAT)) AS datetime),0) [Avg exit time] FROM TimeSheet TS INNER JOIN [User]U ON U.Id = TS.UserId
	 WHERE CompanyId = (SELECT CompanyId FROM [User] WHERE Id = ''@OperationsPerformedBy'' AND InActiveDateTime IS NULL) 
	 GROUP BY FORMAT([Date],''dd-MM-yy''))T'
	WHERE CustomWidgetName = 'Average Exit Time' AND CompanyId = @CompanyId

	UPDATE CustomWidgets SET InActiveDateTime = GETDATE()
	WHERE CustomWidgetName IN ('Employee Intime VS break < 30 mins','Employee lunch out Vs break < 30 mins') AND CompanyId = @CompanyId

END
GO
