CREATE PROCEDURE [dbo].[Marker264]
(
    @CompanyId UNIQUEIDENTIFIER,
    @UserId UNIQUEIDENTIFIER,
    @RoleId UNIQUEIDENTIFIER
)
AS 
BEGIN 
SET NOCOUNT ON

IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'ManagerEmployeeRosterTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'ManagerEmployeeRosterTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'ManagerEmployeeRosterTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'EmployeeRosterDayWiseAmountAfterApproveTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'EmployeeRosterDayWiseAmountAfterApproveTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'EmployeeRosterDayWiseAmountAfterApproveTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'Warning letter' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'Warning letter' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'Warning letter'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'LeaveApplicationTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'LeaveApplicationTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'LeaveApplicationTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'ProjectMemberAddedEmailTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'ProjectMemberAddedEmailTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'ProjectMemberAddedEmailTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'Snovasys Exit Interview' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'Snovasys Exit Interview' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'Snovasys Exit Interview'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'Seniors Developer Offer Letter Without Bond' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'Seniors Developer Offer Letter Without Bond' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'Seniors Developer Offer Letter Without Bond'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'GoalReplanChangesTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'GoalReplanChangesTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'GoalReplanChangesTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'Snovasys Company Requested Resignation Letter' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'Snovasys Company Requested Resignation Letter' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'Snovasys Company Requested Resignation Letter'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'AuditReportMailTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'AuditReportMailTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'AuditReportMailTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'UserReportToNotificationTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'UserReportToNotificationTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'UserReportToNotificationTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'ProjectCreationEmailTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'ProjectCreationEmailTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'ProjectCreationEmailTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'SprintApprovedEmailTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'SprintApprovedEmailTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'SprintApprovedEmailTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'PayslipDetailsTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'PayslipDetailsTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'PayslipDetailsTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'Fresher Appointment letter' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'Fresher Appointment letter' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'Fresher Appointment letter'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'ProjectMemberRemovedEmailTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'ProjectMemberRemovedEmailTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'ProjectMemberRemovedEmailTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'Fresher Offer letter' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'Fresher Offer letter' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'Fresher Offer letter'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'Non Disclosure Agreement new' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'Non Disclosure Agreement new' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'Non Disclosure Agreement new'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'Salary Hike And Special Allowance Letter' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'Salary Hike And Special Allowance Letter' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'Salary Hike And Special Allowance Letter'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'CompanyRegistrationTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'CompanyRegistrationTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'CompanyRegistrationTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'SplitBarChartTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'SplitBarChartTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'SplitBarChartTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'Business development manager offer letter' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'Business development manager offer letter' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'Business development manager offer letter'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'AssetsTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'AssetsTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'AssetsTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'UserStoryAssignedEmailTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'UserStoryAssignedEmailTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'UserStoryAssignedEmailTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'Snovasys Hike Letter' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'Snovasys Hike Letter' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'Snovasys Hike Letter'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'UserSignatureInvitationTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'UserSignatureInvitationTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'UserSignatureInvitationTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'SprintReplanChangesTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'SprintReplanChangesTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'SprintReplanChangesTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'UserReminderTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'UserReminderTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'UserReminderTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'CompanyRegistrationDemoDataTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'CompanyRegistrationDemoDataTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'CompanyRegistrationDemoDataTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'EmployeeRosterTimesheetAfterRejectionTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'EmployeeRosterTimesheetAfterRejectionTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'EmployeeRosterTimesheetAfterRejectionTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'Contract Employee Offer Letter' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'Contract Employee Offer Letter' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'Contract Employee Offer Letter'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'ExpensePDFTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'ExpensePDFTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'ExpensePDFTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'SalaryHikesTable' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'SalaryHikesTable' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'SalaryHikesTable'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'Employee Termination Letter Without Probation clearence - Probation Not Completed' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'Employee Termination Letter Without Probation clearence - Probation Not Completed' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'Employee Termination Letter Without Probation clearence - Probation Not Completed'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'InvoiceMailTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'InvoiceMailTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'InvoiceMailTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'UserStoryUpdateEmailTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'UserStoryUpdateEmailTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'UserStoryUpdateEmailTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'ActivityTrackerTrackingEmailTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'ActivityTrackerTrackingEmailTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'ActivityTrackerTrackingEmailTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'AssetNotificationTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'AssetNotificationTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'AssetNotificationTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'InvoicePDFTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'InvoicePDFTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'InvoicePDFTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'Senior QA offer letter with Bond' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'Senior QA offer letter with Bond' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'Senior QA offer letter with Bond'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'Experience Letter of HR' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'Experience Letter of HR' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'Experience Letter of HR'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'Snovasys Relieving Letter' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'Snovasys Relieving Letter' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'Snovasys Relieving Letter'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'Prohibition completion letter' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'Prohibition completion letter' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'Prohibition completion letter'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'TestRailReportTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'TestRailReportTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'TestRailReportTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'Experirence Letter of Developer' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'Experirence Letter of Developer' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'Experirence Letter of Developer'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'Junior Developer Offer Letter With Special Allowance' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'Junior Developer Offer Letter With Special Allowance' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'Junior Developer Offer Letter With Special Allowance'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'PayrollSendNotification' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'PayrollSendNotification' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'PayrollSendNotification'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'ManagerEmployeeRosterApproveTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'ManagerEmployeeRosterApproveTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'ManagerEmployeeRosterApproveTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'ScenarioExportMailTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'ScenarioExportMailTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'ScenarioExportMailTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'UserRegistrationNotificationTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'UserRegistrationNotificationTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'UserRegistrationNotificationTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'EmployeeRosterTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'EmployeeRosterTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'EmployeeRosterTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'EmployeeRosterDayFinishTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'EmployeeRosterDayFinishTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'EmployeeRosterDayFinishTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'Lead Generation Executive offer letter' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'Lead Generation Executive offer letter' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'Lead Generation Executive offer letter'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'EmployeeRosterCompletionReport' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'EmployeeRosterCompletionReport' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'EmployeeRosterCompletionReport'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'SprintRequestedForReplanEmailTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'SprintRequestedForReplanEmailTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'SprintRequestedForReplanEmailTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'MessengerFeedbackEmailTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'MessengerFeedbackEmailTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'MessengerFeedbackEmailTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'Self Confirmation For Certificate Submission of candidate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'Self Confirmation For Certificate Submission of candidate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'Self Confirmation For Certificate Submission of candidate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'UserPerformanceReviewInvitationTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'UserPerformanceReviewInvitationTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'UserPerformanceReviewInvitationTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'Business Analyst offer letter' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'Business Analyst offer letter' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'Business Analyst offer letter'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'PayslipEmailTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'PayslipEmailTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'PayslipEmailTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'Internship Completion Letter' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'Internship Completion Letter' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'Internship Completion Letter'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'VisualizationTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'VisualizationTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'VisualizationTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'GoalRequestedForReplanEmailTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'GoalRequestedForReplanEmailTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'GoalRequestedForReplanEmailTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'BurndownTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'BurndownTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'BurndownTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'CtcBreakUpTable' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'CtcBreakUpTable' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'CtcBreakUpTable'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'QA offer letter Juniors' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'QA offer letter Juniors' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'QA offer letter Juniors'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'Poor Performance review letter' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'Poor Performance review letter' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'Poor Performance review letter'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'PayslipDeductionsComponentTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'PayslipDeductionsComponentTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'PayslipDeductionsComponentTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'UserStoryCommentEmailTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'UserStoryCommentEmailTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'UserStoryCommentEmailTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'RemoteSiteCompanyRegistrationTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'RemoteSiteCompanyRegistrationTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'RemoteSiteCompanyRegistrationTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'Work From Home Policy' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'Work From Home Policy' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'Work From Home Policy'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'PayslipComponentTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'PayslipComponentTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'PayslipComponentTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'Internship Invitation Letter' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'Internship Invitation Letter' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'Internship Invitation Letter'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'GoalApprovedEmailTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'GoalApprovedEmailTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'GoalApprovedEmailTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'EmployeeRosterTimesheetSubmissionTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'EmployeeRosterTimesheetSubmissionTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'EmployeeRosterTimesheetSubmissionTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'ManagerRosterCompletionReport' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'ManagerRosterCompletionReport' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'ManagerRosterCompletionReport'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'Suspend Letter' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'Suspend Letter' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'Suspend Letter'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'ExpenseMailTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'ExpenseMailTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'ExpenseMailTemplate'    END
IF(EXISTS (SELECT Id FROM [HtmlTemplates] WHERE TemplateName = 'SalaryCertificateTemplate' AND CompanyId = @CompanyId))  BEGIN        UPDATE [HtmlTemplates] SET InActiveDateTime = NULL WHERE TemplateName = 'SalaryCertificateTemplate' AND CompanyId = @CompanyId     END  ELSE  BEGIN      INSERT INTO [HtmlTemplates](Id,TemplateName,HtmlTemplate,CreatedByUserId,CreatedDateTime,CompanyId)   SELECT TOP(1) NEWID(),TemplateName,HtmlTemplate,@UserId,GETDATE(),@CompanyId   FROM [HtmlTemplates]   WHERE TemplateName = 'SalaryCertificateTemplate'    END

DELETE FROM HtmlTemplates
WHERE TemplateName IN 
(
'ManagerEmployeeRosterTemplate'
,'EmployeeRosterDayWiseAmountAfterApproveTemplate'
,'Warning letter'
,'LeaveApplicationTemplate'
,'ProjectMemberAddedEmailTemplate'
,'Snovasys Exit Interview'
,'Seniors Developer Offer Letter Without Bond'
,'GoalReplanChangesTemplate'
,'Snovasys Company Requested Resignation Letter'
,'AuditReportMailTemplate'
,'UserReportToNotificationTemplate'
,'ProjectCreationEmailTemplate'
,'SprintApprovedEmailTemplate'
,'PayslipDetailsTemplate'
,'Fresher Appointment letter'
,'ProjectMemberRemovedEmailTemplate'
,'Fresher Offer letter'
,'Non Disclosure Agreement new'
,'Salary Hike And Special Allowance Letter'
,'CompanyRegistrationTemplate'
,'SplitBarChartTemplate'
,'Business development manager offer letter'
,'AssetsTemplate'
,'UserStoryAssignedEmailTemplate'
,'Snovasys Hike Letter'
,'UserSignatureInvitationTemplate'
,'SprintReplanChangesTemplate'
,'UserReminderTemplate'
,'CompanyRegistrationDemoDataTemplate'
,'EmployeeRosterTimesheetAfterRejectionTemplate'
,'Contract Employee Offer Letter'
,'ExpensePDFTemplate'
,'SalaryHikesTable'
,'Employee Termination Letter Without Probation clearence - Probation Not Completed'
,'InvoiceMailTemplate'
,'UserStoryUpdateEmailTemplate'
,'ActivityTrackerTrackingEmailTemplate'
,'AssetNotificationTemplate'
,'InvoicePDFTemplate'
,'Senior QA offer letter with Bond'
,'Experience Letter of HR'
,'Snovasys Relieving Letter'
,'Prohibition completion letter'
,'TestRailReportTemplate'
,'Experirence Letter of Developer'
,'Junior Developer Offer Letter With Special Allowance'
,'PayrollSendNotification'
,'ManagerEmployeeRosterApproveTemplate'
,'ScenarioExportMailTemplate'
,'UserRegistrationNotificationTemplate'
,'EmployeeRosterTemplate'
,'EmployeeRosterDayFinishTemplate'
,'Lead Generation Executive offer letter'
,'EmployeeRosterCompletionReport'
,'SprintRequestedForReplanEmailTemplate'
,'MessengerFeedbackEmailTemplate'
,'Self Confirmation For Certificate Submission of candidate'
,'UserPerformanceReviewInvitationTemplate'
,'Business Analyst offer letter'
,'PayslipEmailTemplate'
,'Internship Completion Letter'
,'VisualizationTemplate'
,'GoalRequestedForReplanEmailTemplate'
,'BurndownTemplate'
,'CtcBreakUpTable'
,'QA offer letter Juniors'
,'Poor Performance review letter'
,'PayslipDeductionsComponentTemplate'
,'UserStoryCommentEmailTemplate'
,'RemoteSiteCompanyRegistrationTemplate'
,'Work From Home Policy'
,'PayslipComponentTemplate'
,'Internship Invitation Letter'
,'GoalApprovedEmailTemplate'
,'EmployeeRosterTimesheetSubmissionTemplate'
,'ManagerRosterCompletionReport'
,'Suspend Letter'
,'ExpenseMailTemplate'
,'SalaryCertificateTemplate'
)
AND CompanyId IS NULL

DELETE FROM HtmlTemplates
WHERE TemplateName IN (
'ResetPasswordTemplate'
,'UserDailyTrackerReportEmailTemplate'
,'UserBirthdayWishesTemplate'
,'RemoteContactMailTemplate'
,'RegistrationVerificationEmailTemplate'
)
AND CompanyId IS NOT NULL

UPDATE HtmlTemplates SET IsConfigurable = 1 
WHERE TemplateName IN ('UserBirthdayWishesTemplate','UserDailyTrackerReportEmailTemplate')

END
GO
