CREATE PROCEDURE [dbo].[Marker401]
(
    @CompanyId UNIQUEIDENTIFIER,
    @UserId UNIQUEIDENTIFIER,
    @RoleId UNIQUEIDENTIFIER
)
AS
BEGIN
    DECLARE @Currentdate DATETIME = GETDATE()

	MERGE INTO [dbo].[TradeTemplateType] AS Target 
        USING ( VALUES
	     (NEWID(), 'BL Draft', '{
  "components": [
    {
      "label": "Columns",
      "columns": [
        {
          "components": [
            {
              "label": "BL Number",
              "labelPosition": "left-left",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {
                "type": "input"
              },
              "inputMask": "",
              "allowMultipleMasks": false,
              "customClass": "",
              "tabindex": "",
              "autocomplete": "",
              "hidden": false,
              "hideLabel": false,
              "showWordCount": false,
              "showCharCount": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "roleView": [],
              "userView": [],
              "roleEdit": [],
              "userEdit": [],
              "dataSource": "",
              "persistent": true,
              "inputFormat": "plain",
              "protected": false,
              "dbIndex": false,
              "case": "",
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": true,
                "pattern": "",
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "minLength": "",
                "maxLength": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false
              },
              "unique": false,
              "errorLabel": "",
              "key": "blNumber",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "textfield",
              "input": true,
              "refreshOn": "",
              "dataGridLabel": false,
              "inputType": "text",
              "id": "etvihr3",
              "defaultValue": ""
            }
          ],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0,
          "size": "md",
          "currentWidth": 6
        },
        {
          "components": [
            {
              "label": "Shipper",
              "labelPosition": "left-left",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {
                "type": "input"
              },
              "inputMask": "",
              "allowMultipleMasks": false,
              "customClass": "",
              "tabindex": "",
              "autocomplete": "",
              "hidden": false,
              "hideLabel": false,
              "showWordCount": false,
              "showCharCount": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "roleView": [],
              "userView": [],
              "roleEdit": [],
              "userEdit": [],
              "dataSource": "",
              "persistent": true,
              "inputFormat": "plain",
              "protected": false,
              "dbIndex": false,
              "case": "",
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": true,
                "pattern": "",
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "minLength": "",
                "maxLength": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false
              },
              "unique": false,
              "errorLabel": "",
              "key": "shipper",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "textfield",
              "input": true,
              "refreshOn": "",
              "dataGridLabel": false,
              "inputType": "text",
              "id": "ea9suuwk",
              "defaultValue": ""
            }
          ],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0,
          "size": "md",
          "currentWidth": 6
        }
      ],
      "autoAdjust": false,
      "customClass": "",
      "hidden": false,
      "hideLabel": false,
      "modalEdit": false,
      "key": "columns",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "columns",
      "input": false,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "clearOnHide": false,
      "refreshOn": "",
      "redrawOn": "",
      "tableView": false,
      "dataGridLabel": false,
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "widget": null,
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "tree": false,
      "id": "e00pqbk"
    },
    {
      "label": "Columns",
      "columns": [
        {
          "components": [
            {
              "label": "Consignee/Order of",
              "labelPosition": "left-left",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {
                "type": "input"
              },
              "inputMask": "",
              "allowMultipleMasks": false,
              "customClass": "",
              "tabindex": "",
              "autocomplete": "",
              "hidden": false,
              "hideLabel": false,
              "showWordCount": false,
              "showCharCount": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "roleView": [],
              "userView": [],
              "roleEdit": [],
              "userEdit": [],
              "dataSource": "",
              "persistent": true,
              "inputFormat": "plain",
              "protected": false,
              "dbIndex": false,
              "case": "",
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": true,
                "pattern": "",
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "minLength": "",
                "maxLength": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false
              },
              "unique": false,
              "errorLabel": "",
              "key": "consigneeOrderOf",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "textfield",
              "input": true,
              "refreshOn": "",
              "dataGridLabel": false,
              "inputType": "text",
              "id": "ev1u71p",
              "defaultValue": ""
            }
          ],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0,
          "size": "md",
          "currentWidth": 6
        },
        {
          "components": [
            {
              "label": "Notify Address",
              "labelPosition": "left-left",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {
                "type": "input"
              },
              "editor": "",
              "autoExpand": false,
              "customClass": "",
              "tabindex": "",
              "autocomplete": "",
              "hidden": false,
              "hideLabel": false,
              "showWordCount": false,
              "showCharCount": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "roleView": [],
              "userView": [],
              "roleEdit": [],
              "userEdit": [],
              "dataSource": "",
              "persistent": true,
              "inputFormat": "html",
              "protected": false,
              "dbIndex": false,
              "case": "",
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": true,
                "pattern": "",
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "minLength": "",
                "maxLength": "",
                "minWords": "",
                "maxWords": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false
              },
              "unique": false,
              "errorLabel": "",
              "key": "notifyAddress",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "textarea",
              "rows": 3,
              "wysiwyg": false,
              "input": true,
              "refreshOn": "",
              "dataGridLabel": false,
              "allowMultipleMasks": false,
              "mask": false,
              "inputType": "text",
              "inputMask": "",
              "fixedSize": true,
              "id": "e0uukyg",
              "defaultValue": ""
            }
          ],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0,
          "size": "md",
          "currentWidth": 6
        }
      ],
      "autoAdjust": false,
      "customClass": "",
      "hidden": false,
      "hideLabel": false,
      "modalEdit": false,
      "key": "columns1",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "columns",
      "input": false,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "clearOnHide": false,
      "refreshOn": "",
      "redrawOn": "",
      "tableView": false,
      "dataGridLabel": false,
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "widget": null,
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "tree": false,
      "id": "ekqqnsq"
    },
    {
      "label": "Columns",
      "columns": [
        {
          "components": [
            {
              "label": "Vessel name",
              "labelPosition": "left-left",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {
                "type": "input"
              },
              "inputMask": "",
              "allowMultipleMasks": false,
              "customClass": "",
              "tabindex": "",
              "autocomplete": "",
              "hidden": false,
              "hideLabel": false,
              "showWordCount": false,
              "showCharCount": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "roleView": [],
              "userView": [],
              "roleEdit": [],
              "userEdit": [],
              "dataSource": "",
              "persistent": true,
              "inputFormat": "plain",
              "protected": false,
              "dbIndex": false,
              "case": "",
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": true,
                "pattern": "",
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "minLength": "",
                "maxLength": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false
              },
              "unique": false,
              "errorLabel": "",
              "key": "vesselName",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "textfield",
              "input": true,
              "refreshOn": "",
              "dataGridLabel": false,
              "inputType": "text",
              "id": "ew04gmi",
              "defaultValue": ""
            }
          ],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0,
          "size": "md",
          "currentWidth": 6
        },
        {
          "components": [
            {
              "label": "Flag",
              "labelPosition": "left-left",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {
                "type": "input"
              },
              "inputMask": "",
              "allowMultipleMasks": false,
              "customClass": "",
              "tabindex": "",
              "autocomplete": "",
              "hidden": false,
              "hideLabel": false,
              "showWordCount": false,
              "showCharCount": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "roleView": [],
              "userView": [],
              "roleEdit": [],
              "userEdit": [],
              "dataSource": "",
              "persistent": true,
              "inputFormat": "plain",
              "protected": false,
              "dbIndex": false,
              "case": "",
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": true,
                "pattern": "",
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "minLength": "",
                "maxLength": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false
              },
              "unique": false,
              "errorLabel": "",
              "key": "flag",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "textfield",
              "input": true,
              "refreshOn": "",
              "dataGridLabel": false,
              "inputType": "text",
              "id": "eny0vc8",
              "defaultValue": ""
            }
          ],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0,
          "size": "md",
          "currentWidth": 6
        }
      ],
      "autoAdjust": false,
      "customClass": "",
      "hidden": false,
      "hideLabel": false,
      "modalEdit": false,
      "key": "columns2",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "columns",
      "input": false,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "clearOnHide": false,
      "refreshOn": "",
      "redrawOn": "",
      "tableView": false,
      "dataGridLabel": false,
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "widget": null,
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "tree": false,
      "id": "eeup7tg"
    },
    {
      "label": "Columns",
      "columns": [
        {
          "components": [
            {
              "label": "Master",
              "labelPosition": "left-left",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {
                "type": "input"
              },
              "inputMask": "",
              "allowMultipleMasks": false,
              "customClass": "",
              "tabindex": "",
              "autocomplete": "",
              "hidden": false,
              "hideLabel": false,
              "showWordCount": false,
              "showCharCount": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "roleView": [],
              "userView": [],
              "roleEdit": [],
              "userEdit": [],
              "dataSource": "",
              "persistent": true,
              "inputFormat": "plain",
              "protected": false,
              "dbIndex": false,
              "case": "",
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": true,
                "pattern": "",
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "minLength": "",
                "maxLength": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false
              },
              "unique": false,
              "errorLabel": "",
              "key": "master",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "textfield",
              "input": true,
              "refreshOn": "",
              "dataGridLabel": false,
              "inputType": "text",
              "id": "eev8o6e",
              "defaultValue": ""
            }
          ],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0,
          "size": "md",
          "currentWidth": 6
        },
        {
          "components": [
            {
              "label": "IMO Number",
              "labelPosition": "left-left",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {
                "type": "input"
              },
              "customClass": "",
              "tabindex": "",
              "autocomplete": "",
              "hidden": false,
              "hideLabel": false,
              "mask": false,
              "autofocus": false,
              "disabled": false,
              "tableView": false,
              "modalEdit": false,
              "multiple": false,
              "roleView": [],
              "userView": [],
              "roleEdit": [],
              "userEdit": [],
              "dataSource": "",
              "persistent": true,
              "delimiter": false,
              "requireDecimal": false,
              "inputFormat": "plain",
              "protected": false,
              "dbIndex": false,
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": true,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "min": "",
                "max": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
                "step": "any",
                "integer": ""
              },
              "errorLabel": "",
              "key": "imoNumber",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "number",
              "input": true,
              "unique": false,
              "refreshOn": "",
              "dataGridLabel": false,
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "id": "eot96od",
              "defaultValue": null
            }
          ],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0,
          "size": "md",
          "currentWidth": 6
        }
      ],
      "autoAdjust": false,
      "customClass": "",
      "hidden": false,
      "hideLabel": false,
      "modalEdit": false,
      "key": "columns3",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "columns",
      "input": false,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "clearOnHide": false,
      "refreshOn": "",
      "redrawOn": "",
      "tableView": false,
      "dataGridLabel": false,
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "widget": null,
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "tree": false,
      "id": "e9d4e5"
    },
    {
      "label": "Columns",
      "columns": [
        {
          "components": [
            {
              "label": "*Port of Loading",
              "labelPosition": "left-left",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {
                "type": "input"
              },
              "inputMask": "",
              "allowMultipleMasks": false,
              "customClass": "",
              "tabindex": "",
              "autocomplete": "",
              "hidden": false,
              "hideLabel": false,
              "showWordCount": false,
              "showCharCount": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "roleView": [],
              "userView": [],
              "roleEdit": [],
              "userEdit": [],
              "dataSource": "",
              "persistent": true,
              "inputFormat": "plain",
              "protected": false,
              "dbIndex": false,
              "case": "",
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": true,
                "pattern": "",
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "minLength": "",
                "maxLength": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false
              },
              "unique": false,
              "errorLabel": "",
              "key": "portOfLoading",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "textfield",
              "input": true,
              "refreshOn": "",
              "dataGridLabel": false,
              "inputType": "text",
              "id": "elvkrz",
              "defaultValue": ""
            }
          ],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0,
          "size": "md",
          "currentWidth": 6
        },
        {
          "components": [
            {
              "label": "*Port of Discharging",
              "labelPosition": "left-left",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {
                "type": "input"
              },
              "inputMask": "",
              "allowMultipleMasks": false,
              "customClass": "",
              "tabindex": "",
              "autocomplete": "",
              "hidden": false,
              "hideLabel": false,
              "showWordCount": false,
              "showCharCount": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "roleView": [],
              "userView": [],
              "roleEdit": [],
              "userEdit": [],
              "dataSource": "",
              "persistent": true,
              "inputFormat": "plain",
              "protected": false,
              "dbIndex": false,
              "case": "",
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": false,
                "pattern": "",
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "minLength": "",
                "maxLength": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false
              },
              "unique": false,
              "errorLabel": "",
              "key": "portOfDischarging",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "textfield",
              "input": true,
              "refreshOn": "",
              "dataGridLabel": false,
              "inputType": "text",
              "id": "e653awi",
              "defaultValue": ""
            }
          ],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0,
          "size": "md",
          "currentWidth": 6
        }
      ],
      "autoAdjust": false,
      "customClass": "",
      "hidden": false,
      "hideLabel": false,
      "modalEdit": false,
      "key": "columns4",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "columns",
      "input": false,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "clearOnHide": false,
      "refreshOn": "",
      "redrawOn": "",
      "tableView": false,
      "dataGridLabel": false,
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "widget": null,
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "tree": false,
      "id": "e9qmjnr"
    },
    {
      "label": "Columns",
      "columns": [
        {
          "components": [
            {
              "label": "Voyage Number",
              "labelPosition": "left-left",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {
                "type": "input"
              },
              "inputMask": "",
              "allowMultipleMasks": false,
              "customClass": "",
              "tabindex": "",
              "autocomplete": "",
              "hidden": false,
              "hideLabel": false,
              "showWordCount": false,
              "showCharCount": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "roleView": [],
              "userView": [],
              "roleEdit": [],
              "userEdit": [],
              "dataSource": "",
              "persistent": true,
              "inputFormat": "plain",
              "protected": false,
              "dbIndex": false,
              "case": "",
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": true,
                "pattern": "",
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "minLength": "",
                "maxLength": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false
              },
              "unique": false,
              "errorLabel": "",
              "key": "voyageNumber",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "textfield",
              "input": true,
              "refreshOn": "",
              "dataGridLabel": false,
              "inputType": "text",
              "id": "e5m545o",
              "defaultValue": ""
            }
          ],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0,
          "size": "md",
          "currentWidth": 6
        },
        {
          "components": [
            {
              "label": "Commodity",
              "labelPosition": "left-left",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {
                "type": "input"
              },
              "inputMask": "",
              "allowMultipleMasks": false,
              "customClass": "",
              "tabindex": "",
              "autocomplete": "",
              "hidden": false,
              "hideLabel": false,
              "showWordCount": false,
              "showCharCount": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "roleView": [],
              "userView": [],
              "roleEdit": [],
              "userEdit": [],
              "dataSource": "",
              "persistent": true,
              "inputFormat": "plain",
              "protected": false,
              "dbIndex": false,
              "case": "",
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": true,
                "pattern": "",
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "minLength": "",
                "maxLength": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false
              },
              "unique": false,
              "errorLabel": "",
              "key": "commodity",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "textfield",
              "input": true,
              "refreshOn": "",
              "dataGridLabel": false,
              "inputType": "text",
              "id": "eu74dme",
              "defaultValue": ""
            }
          ],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0,
          "size": "md",
          "currentWidth": 6
        }
      ],
      "autoAdjust": false,
      "customClass": "",
      "hidden": false,
      "hideLabel": false,
      "modalEdit": false,
      "key": "columns5",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "columns",
      "input": false,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "clearOnHide": false,
      "refreshOn": "",
      "redrawOn": "",
      "tableView": false,
      "dataGridLabel": false,
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "widget": null,
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "tree": false,
      "id": "eqz0pl"
    },
    {
      "label": "Columns",
      "columns": [
        {
          "components": [
            {
              "label": "Total Quantity (MT)",
              "labelPosition": "left-left",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {
                "type": "input"
              },
              "customClass": "",
              "tabindex": "",
              "autocomplete": "",
              "hidden": false,
              "hideLabel": false,
              "mask": false,
              "autofocus": false,
              "disabled": false,
              "tableView": false,
              "modalEdit": false,
              "multiple": false,
              "roleView": [],
              "userView": [],
              "roleEdit": [],
              "userEdit": [],
              "dataSource": "",
              "persistent": true,
              "delimiter": false,
              "requireDecimal": false,
              "inputFormat": "plain",
              "protected": false,
              "dbIndex": false,
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": true,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "min": "",
                "max": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
                "step": "any",
                "integer": ""
              },
              "errorLabel": "",
              "key": "totalQuantityMt",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "number",
              "input": true,
              "unique": false,
              "refreshOn": "",
              "dataGridLabel": false,
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "id": "ei6whdc",
              "defaultValue": null
            }
          ],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0,
          "size": "md",
          "currentWidth": 6
        },
        {
          "components": [
            {
              "label": "Ocean carriage stowage",
              "labelPosition": "left-left",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {
                "type": "input"
              },
              "inputMask": "",
              "allowMultipleMasks": false,
              "customClass": "",
              "tabindex": "",
              "autocomplete": "",
              "hidden": false,
              "hideLabel": false,
              "showWordCount": false,
              "showCharCount": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "roleView": [],
              "userView": [],
              "roleEdit": [],
              "userEdit": [],
              "dataSource": "",
              "persistent": true,
              "inputFormat": "plain",
              "protected": false,
              "dbIndex": false,
              "case": "",
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": true,
                "pattern": "",
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "minLength": "",
                "maxLength": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false
              },
              "unique": false,
              "errorLabel": "",
              "key": "oceanCarriageStowage",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "textfield",
              "input": true,
              "refreshOn": "",
              "dataGridLabel": false,
              "inputType": "text",
              "id": "ekr0lw",
              "defaultValue": null
            }
          ],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0,
          "size": "md",
          "currentWidth": 6
        }
      ],
      "autoAdjust": false,
      "customClass": "",
      "hidden": false,
      "hideLabel": false,
      "modalEdit": false,
      "key": "columns6",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "columns",
      "input": false,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "clearOnHide": false,
      "refreshOn": "",
      "redrawOn": "",
      "tableView": false,
      "dataGridLabel": false,
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "widget": null,
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "tree": false,
      "id": "etzwwo9"
    },
    {
      "label": "Charterer",
      "labelPosition": "left-left",
      "placeholder": "",
      "description": "",
      "tooltip": "",
      "prefix": "",
      "suffix": "",
      "widget": {
        "type": "input"
      },
      "editor": "",
      "autoExpand": false,
      "customClass": "",
      "tabindex": "",
      "autocomplete": "",
      "hidden": false,
      "hideLabel": false,
      "showWordCount": false,
      "showCharCount": false,
      "autofocus": false,
      "spellcheck": true,
      "disabled": false,
      "tableView": true,
      "modalEdit": false,
      "multiple": false,
      "roleView": [],
      "userView": [],
      "roleEdit": [],
      "userEdit": [],
      "dataSource": "",
      "persistent": true,
      "inputFormat": "html",
      "protected": false,
      "dbIndex": false,
      "case": "",
      "encrypted": false,
      "redrawOn": "",
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validateOn": "change",
      "validate": {
        "required": true,
        "pattern": "",
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "minLength": "",
        "maxLength": "",
        "minWords": "",
        "maxWords": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "unique": false,
      "errorLabel": "",
      "key": "charterer",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "textarea",
      "rows": 3,
      "wysiwyg": false,
      "input": true,
      "refreshOn": "",
      "dataGridLabel": false,
      "allowMultipleMasks": false,
      "mask": false,
      "inputType": "text",
      "inputMask": "",
      "fixedSize": true,
      "id": "es1ada",
      "defaultValue": ""
    },
    {
      "label": "Columns",
      "columns": [
        {
          "components": [
            {
              "label": "Vessel owner",
              "labelPosition": "left-left",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {
                "type": "input"
              },
              "inputMask": "",
              "allowMultipleMasks": false,
              "customClass": "",
              "tabindex": "",
              "autocomplete": "",
              "hidden": false,
              "hideLabel": false,
              "showWordCount": false,
              "showCharCount": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "roleView": [],
              "userView": [],
              "roleEdit": [],
              "userEdit": [],
              "dataSource": "",
              "persistent": true,
              "inputFormat": "plain",
              "protected": false,
              "dbIndex": false,
              "case": "",
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": true,
                "pattern": "",
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "minLength": "",
                "maxLength": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false
              },
              "unique": false,
              "errorLabel": "",
              "key": "vesselOwner",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "textfield",
              "input": true,
              "refreshOn": "",
              "dataGridLabel": false,
              "inputType": "text",
              "id": "ewr8fu",
              "defaultValue": ""
            }
          ],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0,
          "size": "md",
          "currentWidth": 6
        },
        {
          "components": [
            {
              "label": "Charterparty date",
              "labelPosition": "left-left",
              "displayInTimezone": "viewer",
              "useLocaleSettings": false,
              "allowInput": true,
              "format": "yyyy-MM-dd hh:mm a",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "autofocus": false,
              "disabled": false,
              "tableView": false,
              "modalEdit": false,
              "shortcutButtons": [],
              "enableDate": true,
              "enableMinDateInput": false,
              "datePicker": {
                "minDate": null,
                "maxDate": null,
                "disable": "",
                "disableFunction": "",
                "disableWeekends": false,
                "disableWeekdays": false,
                "showWeeks": true,
                "startingDay": 0,
                "initDate": "",
                "minMode": "day",
                "maxMode": "year",
                "yearRows": 4,
                "yearColumns": 5
              },
              "enableMaxDateInput": false,
              "enableTime": true,
              "timePicker": {
                "showMeridian": true,
                "hourStep": 1,
                "minuteStep": 1,
                "readonlyInput": false,
                "mousewheel": true,
                "arrowkeys": true
              },
              "multiple": false,
              "defaultValue": "",
              "defaultDate": "",
              "customOptions": {},
              "persistent": true,
              "protected": false,
              "dbIndex": false,
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "allowCalculateOverride": false,
              "validate": {
                "required": true,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false
              },
              "unique": false,
              "validateOn": "change",
              "errorLabel": "",
              "key": "charterpartyDate",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "datetime",
              "timezone": "",
              "input": true,
              "prefix": "",
              "suffix": "",
              "refreshOn": "",
              "dataGridLabel": false,
              "widget": {
                "type": "calendar",
                "displayInTimezone": "viewer",
                "locale": "en",
                "useLocaleSettings": false,
                "allowInput": true,
                "mode": "single",
                "enableTime": true,
                "noCalendar": false,
                "format": "yyyy-MM-dd hh:mm a",
                "hourIncrement": 1,
                "minuteIncrement": 1,
                "time_24hr": false,
                "minDate": null,
                "disabledDates": "",
                "disableWeekends": false,
                "disableWeekdays": false,
                "disableFunction": "",
                "maxDate": null
              },
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "datepickerMode": "day",
              "id": "e6trwdg"
            }
          ],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0,
          "size": "md",
          "currentWidth": 6
        }
      ],
      "autoAdjust": false,
      "customClass": "",
      "hidden": false,
      "hideLabel": false,
      "modalEdit": false,
      "key": "columns7",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "columns",
      "input": false,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "clearOnHide": false,
      "refreshOn": "",
      "redrawOn": "",
      "tableView": false,
      "dataGridLabel": false,
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "widget": null,
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "tree": false,
      "id": "elqyyb"
    },
    {
      "label": "Columns",
      "columns": [
        {
          "components": [
            {
              "label": "Place of issue",
              "labelPosition": "left-left",
              "widget": "choicesjs",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "uniqueOptions": false,
              "autofocus": false,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "dataSrc": "url",
              "roleView": [],
              "userView": [],
              "roleEdit": [],
              "userEdit": [],
              "dataSource": "",
              "data": {
                "resource": "",
                "json": "",
                "url": "https://test-btrak515.nxusworld.com/SystemManagement/SystemManagementApi/SearchSystemCountries?Id",
                "custom": "",
                "headers": [
                  {
                    "key": "Id",
                    "value": "null"
                  }
                ],
                "values": [
                  {
                    "label": "",
                    "value": ""
                  }
                ]
              },
              "dataType": "",
              "idPath": "id",
              "valueProperty": "",
              "template": "<span>{{ data.countryName }}</span>",
              "refreshOn": "",
              "refreshOnBlur": "",
              "clearOnRefresh": false,
              "searchEnabled": true,
              "selectThreshold": 0.3,
              "readOnlyValue": false,
              "customOptions": {},
              "useExactSearch": false,
              "persistent": true,
              "protected": false,
              "dbIndex": false,
              "encrypted": false,
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": true,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
                "onlyAvailableItems": false
              },
              "unique": false,
              "errorLabel": "",
              "key": "placeOfIssue",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "select",
              "indexeddb": {
                "filter": {}
              },
              "selectFields": "",
              "searchField": "",
              "minSearch": 0,
              "filter": "",
              "limit": 100,
              "redrawOn": "",
              "input": true,
              "prefix": "",
              "suffix": "",
              "dataGridLabel": false,
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "lazyLoad": true,
              "authenticate": false,
              "ignoreCache": false,
              "fuseOptions": {
                "include": "score",
                "threshold": 0.3
              },
              "id": "ef9gt8n",
              "defaultValue": "",
              "selectValues": "data",
              "disableLimit": false,
              "sort": ""
            }
          ],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0,
          "size": "md",
          "currentWidth": 6
        },
        {
          "components": [
            {
              "label": "BL issue date",
              "labelPosition": "left-left",
              "displayInTimezone": "viewer",
              "useLocaleSettings": false,
              "allowInput": true,
              "format": "yyyy-MM-dd hh:mm a",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "autofocus": false,
              "disabled": false,
              "tableView": false,
              "modalEdit": false,
              "shortcutButtons": [],
              "enableDate": true,
              "enableMinDateInput": false,
              "datePicker": {
                "minDate": null,
                "maxDate": null,
                "disable": "",
                "disableFunction": "",
                "disableWeekends": false,
                "disableWeekdays": false,
                "showWeeks": true,
                "startingDay": 0,
                "initDate": "",
                "minMode": "day",
                "maxMode": "year",
                "yearRows": 4,
                "yearColumns": 5
              },
              "enableMaxDateInput": false,
              "enableTime": true,
              "timePicker": {
                "showMeridian": true,
                "hourStep": 1,
                "minuteStep": 1,
                "readonlyInput": false,
                "mousewheel": true,
                "arrowkeys": true
              },
              "multiple": false,
              "defaultValue": "",
              "defaultDate": "",
              "customOptions": {},
              "persistent": true,
              "protected": false,
              "dbIndex": false,
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "allowCalculateOverride": false,
              "validate": {
                "required": true,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false
              },
              "unique": false,
              "validateOn": "change",
              "errorLabel": "",
              "key": "blIssueDate",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "datetime",
              "timezone": "",
              "input": true,
              "prefix": "",
              "suffix": "",
              "refreshOn": "",
              "dataGridLabel": false,
              "widget": {
                "type": "calendar",
                "displayInTimezone": "viewer",
                "locale": "en",
                "useLocaleSettings": false,
                "allowInput": true,
                "mode": "single",
                "enableTime": true,
                "noCalendar": false,
                "format": "yyyy-MM-dd hh:mm a",
                "hourIncrement": 1,
                "minuteIncrement": 1,
                "time_24hr": false,
                "minDate": null,
                "disabledDates": "",
                "disableWeekends": false,
                "disableWeekdays": false,
                "disableFunction": "",
                "maxDate": null
              },
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "datepickerMode": "day",
              "id": "epc34da"
            }
          ],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0,
          "size": "md",
          "currentWidth": 6
        }
      ],
      "autoAdjust": false,
      "customClass": "",
      "hidden": false,
      "hideLabel": false,
      "modalEdit": false,
      "key": "columns8",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "columns",
      "input": false,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "clearOnHide": false,
      "refreshOn": "",
      "redrawOn": "",
      "tableView": false,
      "dataGridLabel": false,
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "widget": null,
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "tree": false,
      "id": "exfiy32"
    },
    {
      "label": "Columns",
      "columns": [
        {
          "components": [
            {
              "label": "Number of sets",
              "labelPosition": "left-left",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {
                "type": "input"
              },
              "inputMask": "",
              "allowMultipleMasks": false,
              "customClass": "",
              "tabindex": "",
              "autocomplete": "",
              "hidden": false,
              "hideLabel": false,
              "showWordCount": false,
              "showCharCount": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "roleView": [],
              "userView": [],
              "roleEdit": [],
              "userEdit": [],
              "dataSource": "",
              "persistent": true,
              "inputFormat": "plain",
              "protected": false,
              "dbIndex": false,
              "case": "",
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": true,
                "pattern": "",
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "minLength": "",
                "maxLength": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false
              },
              "unique": false,
              "errorLabel": "",
              "key": "numberOfSets",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "textfield",
              "input": true,
              "refreshOn": "",
              "dataGridLabel": false,
              "inputType": "text",
              "id": "ehslzc5",
              "defaultValue": ""
            }
          ],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0,
          "size": "md",
          "currentWidth": 6
        },
        {
          "components": [],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0,
          "size": "md",
          "currentWidth": 6
        }
      ],
      "autoAdjust": false,
      "customClass": "",
      "hidden": false,
      "hideLabel": false,
      "modalEdit": false,
      "key": "columns9",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "columns",
      "input": false,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "clearOnHide": false,
      "refreshOn": "",
      "redrawOn": "",
      "tableView": false,
      "dataGridLabel": false,
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "widget": null,
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "tree": false,
      "id": "esfo5im"
    },
    {
      "type": "button",
      "label": "Submit",
      "key": "submit",
      "size": "md",
      "block": false,
      "action": "submit",
      "disableOnInvalid": true,
      "theme": "primary",
      "input": true,
      "placeholder": "",
      "prefix": "",
      "customClass": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "hidden": false,
      "clearOnHide": true,
      "refreshOn": "",
      "redrawOn": "",
      "tableView": false,
      "modalEdit": false,
      "dataGridLabel": true,
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "hideLabel": false,
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "widget": {
        "type": "input"
      },
      "attributes": {},
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "conditional": {
        "show": null,
        "when": null,
        "eq": ""
      },
      "overlay": {
        "style": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "properties": {},
      "allowMultipleMasks": false,
      "leftIcon": "",
      "rightIcon": "",
      "id": "e9lw5pc"
    }
  ]
}', @Currentdate, @UserId,@CompanyId, NULL)
        )
        AS Source ([Id], [TemplateTypeName], [FormJson], [CreatedDateTime], [CreatedByUserId],[CompanyId],[InActiveDateTime])
        ON Target.[TemplateTypeName] = Source.[TemplateTypeName]  AND Target.CompanyId=Source.CompanyId
        WHEN MATCHED THEN 
        UPDATE SET [Id] = Source.[Id],
                   [TemplateTypeName] = Source.[TemplateTypeName],
                   [FormJson] = Source.[FormJson],
                   [CompanyId] = Source.[CompanyId],
                   [CreatedDateTime] = Source.[CreatedDateTime],
                   [CreatedByUserId] = Source.[CreatedByUserId]
        WHEN NOT MATCHED BY TARGET THEN 
        INSERT ([Id], [TemplateTypeName], [FormJson], [CreatedDateTime], [CreatedByUserId], [CompanyId],[InActiveDateTime]) 
        VALUES ([Id], [TemplateTypeName], [FormJson], [CreatedDateTime], [CreatedByUserId], [CompanyId],[InActiveDateTime]);

END
GO