CREATE PROCEDURE [dbo].[Marker143]
(
    @CompanyId UNIQUEIDENTIFIER,
    @UserId UNIQUEIDENTIFIER,
    @RoleId UNIQUEIDENTIFIER
)
AS 
BEGIN 

UPDATE CustomWidgets SET [Description] = 'This app provides the counts of each month joined employeed in the trend graph.Users can download the information in the app 
and can change the visualization of the app and they can filter data in the app' WHERE CustomWidgetName =  'Employees Count Vs Join Date'  AND CompanyId = @CompanyId

UPDATE CustomWidgets SET [Description] = 'This app provides the counts of today joined employeed.Users can download the information in the app 
and can change the visualization of the app and they can filter data in the app' WHERE CustomWidgetName =  'Employees Joined Today' AND CompanyId = @CompanyId

UPDATE CustomWidgets SET [Description] = 'This app provides the counts of invoices which are need to paid.Users can download the information in the app 
and can change the visualization of the app and they can filter data in the app' WHERE CustomWidgetName =  'Invoices Due' AND CompanyId = @CompanyId

UPDATE CustomWidgets SET [Description] =  'This app provides the counts of invoices which are need to paid even deadline crossed.Users can download the information in the app 
and can change the visualization of the app and they can filter data in the app' WHERE CustomWidgetName =  'Invoices Overdue' AND CompanyId = @CompanyId

  UPDATE CustomAppColumns SET ColumnName = 'Retest percent' WHERE ColumnName ='Restest percent' AND CustomWidgetId IN (SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All testruns ' AND CompanyId = @CompanyId)

MERGE INTO [dbo].[CustomAppColumns] AS Target
USING ( VALUES
 ((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Yesterday team spent time' AND CompanyId = @CompanyId),'Yesterday team spent time','varchar',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Yesterday QA raised issues' AND CompanyId = @CompanyId),'Yesterday QA raised issues','int',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Yesterday planned vs unplanned work percentage' AND CompanyId = @CompanyId),'Planned work','decimal',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Yesterday planned vs unplanned work percentage' AND CompanyId = @CompanyId),'Un planned work','decimal',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Yesterday logging compliance' AND CompanyId = @CompanyId),'Id','uniqueidentifier',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Yesterday logging compliance' AND CompanyId = @CompanyId),'Responsible','nvarchar',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Yesterday logging compliance' AND CompanyId = @CompanyId),'Compliance %','decimal',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Yesterday logging compliance' AND CompanyId = @CompanyId),'Non Compliant Members','nvarchar',4)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Yesterday late people count' AND CompanyId = @CompanyId),'Late people count','nvarchar',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Yesterday break time' AND CompanyId = @CompanyId),'Yesterday break time','varchar',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Work Items Due Soon' AND CompanyId = @CompanyId),'Work Items Due Soon','int',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Version details' AND CompanyId = @CompanyId),'Milestone name','nvarchar',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Version details' AND CompanyId = @CompanyId),'Id','uniqueidentifier',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Version details' AND CompanyId = @CompanyId),'Blocked count','int',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Version details' AND CompanyId = @CompanyId),'Failed count','int',4)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Version details' AND CompanyId = @CompanyId),'Passed count','int',5)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Version details' AND CompanyId = @CompanyId),'Untested count','int',6)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Version details' AND CompanyId = @CompanyId),'Retest count','int',7)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Unassigned assets' AND CompanyId = @CompanyId),'Unassigned assets','int',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Today''s work items ' AND CompanyId = @CompanyId),'Work item','nvarchar',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Today''s work items ' AND CompanyId = @CompanyId),'Goal name','nvarchar',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Today''s work items ' AND CompanyId = @CompanyId),'Sprint name','nvarchar',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Today''s work items ' AND CompanyId = @CompanyId),'Id','uniqueidentifier',4)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Today''s work items ' AND CompanyId = @CompanyId),'GoalId','uniqueidentifier',5)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Today''s work items ' AND CompanyId = @CompanyId),'SprintId','uniqueidentifier',6)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'This week productivity' AND CompanyId = @CompanyId),'This week productivity','numeric',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'This month company productivity' AND CompanyId = @CompanyId),' This month company productivity ','int',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'TestCases priority wise' AND CompanyId = @CompanyId),'Testsuite name ','nvarchar',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'TestCases priority wise' AND CompanyId = @CompanyId),'High priority count','int',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'TestCases priority wise' AND CompanyId = @CompanyId),'Id','uniqueidentifier',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'TestCases priority wise' AND CompanyId = @CompanyId),'Low priority count','int',4)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'TestCases priority wise' AND CompanyId = @CompanyId),'Critical priority count','int',5)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'TestCases priority wise' AND CompanyId = @CompanyId),'Medium priority count','int',6)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Spent time VS productive time' AND CompanyId = @CompanyId),'Id','uniqueidentifier',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Spent time VS productive time' AND CompanyId = @CompanyId),'Employee name','nvarchar',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Spent time VS productive time' AND CompanyId = @CompanyId),'Spent time','varchar',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Spent time VS productive time' AND CompanyId = @CompanyId),'Productivity','int',4)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Section details for all scenarios' AND CompanyId = @CompanyId),'Id','uniqueidentifier',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Section details for all scenarios' AND CompanyId = @CompanyId),'SectionId','uniqueidentifier',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Section details for all scenarios' AND CompanyId = @CompanyId),'Section name','nvarchar',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Section details for all scenarios' AND CompanyId = @CompanyId),'Cases count','int',4)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Section details for all scenarios' AND CompanyId = @CompanyId),'P0 bugs','int',5)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Section details for all scenarios' AND CompanyId = @CompanyId),'P1 bugs','int',6)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Section details for all scenarios' AND CompanyId = @CompanyId),'P2 bugs','int',7)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Section details for all scenarios' AND CompanyId = @CompanyId),'P3 bugs','int',8)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Section details for all scenarios' AND CompanyId = @CompanyId),'Total bugs','int',9)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Section details for all scenarios' AND CompanyId = @CompanyId),'Estimate','varchar',10)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Red goals list' AND CompanyId = @CompanyId),'Goal name','nvarchar',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Red goals list' AND CompanyId = @CompanyId),'Id','uniqueidentifier',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Red goals list' AND CompanyId = @CompanyId),'Goal responsible person','nvarchar',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Project wise bugs count' AND CompanyId = @CompanyId),'ProjectName','nvarchar',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Project wise bugs count' AND CompanyId = @CompanyId),'StatusCounts','int',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Project wise bugs count' AND CompanyId = @CompanyId),'Id','uniqueidentifier',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Productivity of this month' AND CompanyId = @CompanyId),'Productivity','numeric',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Productivity indexes for this month' AND CompanyId = @CompanyId),'Id','uniqueidentifier',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Productivity indexes for this month' AND CompanyId = @CompanyId),'Employee name','nvarchar',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Productivity indexes for this month' AND CompanyId = @CompanyId),'Spent time','varchar',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Productivity indexes for this month' AND CompanyId = @CompanyId),'Productivity','decimal',4)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Productivity Indexes by project for this month' AND CompanyId = @CompanyId),'ProjectName','nvarchar',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Productivity Indexes by project for this month' AND CompanyId = @CompanyId),'Id','uniqueidentifier',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Productivity Indexes by project for this month' AND CompanyId = @CompanyId),'Productiviy Index by project','numeric',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Planned work Vs unplanned work team wise' AND CompanyId = @CompanyId),'Lead name','nvarchar',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Planned work Vs unplanned work team wise' AND CompanyId = @CompanyId),'Id','uniqueidentifier',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Planned work Vs unplanned work team wise' AND CompanyId = @CompanyId),'Planned work percent','decimal',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Planned work Vs unplanned work team wise' AND CompanyId = @CompanyId),'Un planned work percent','decimal',4)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Planned work VS unplanned work employee wise' AND CompanyId = @CompanyId),'Id','uniqueidentifier',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Planned work VS unplanned work employee wise' AND CompanyId = @CompanyId),'Employee name','nvarchar',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Planned work VS unplanned work employee wise' AND CompanyId = @CompanyId),'Planned work percent','decimal',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Planned work VS unplanned work employee wise' AND CompanyId = @CompanyId),'Unplanned work percent','decimal',4)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Pipeline work' AND CompanyId = @CompanyId),'Goal name','nvarchar',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Pipeline work' AND CompanyId = @CompanyId),'Sprint name','nvarchar',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Pipeline work' AND CompanyId = @CompanyId),'Work item name','nvarchar',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Pipeline work' AND CompanyId = @CompanyId),'Deadline','datetimeoffset',4)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Pipeline work' AND CompanyId = @CompanyId),'Deadline date','nvarchar',5)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Pipeline work' AND CompanyId = @CompanyId),'Id','uniqueidentifier',6)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Pipeline work' AND CompanyId = @CompanyId),'SprintId','uniqueidentifier',7)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Pipeline work' AND CompanyId = @CompanyId),'GoalId','uniqueidentifier',8)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'People without finish yesterday' AND CompanyId = @CompanyId),'People without finish yesterday','int',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Pending assets' AND CompanyId = @CompanyId),'Pending assets','int',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Night late people count' AND CompanyId = @CompanyId),'Night late people count','int',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Night late employees' AND CompanyId = @CompanyId),'Employee name','nvarchar',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Night late employees' AND CompanyId = @CompanyId),'Date','date',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Night late employees' AND CompanyId = @CompanyId),'Out Time','time',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Night late employees' AND CompanyId = @CompanyId),'Spent time','decimal',4)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Night late employees' AND CompanyId = @CompanyId),'Id','uniqueidentifier',5)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Morning late employees' AND CompanyId = @CompanyId),'Date','date',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Morning late employees' AND CompanyId = @CompanyId),'Employee name','nvarchar',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Morning late employees' AND CompanyId = @CompanyId),'Id','uniqueidentifier',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Long running items' AND CompanyId = @CompanyId),'Long running items','int',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Leaves waiting for approval' AND CompanyId = @CompanyId),'Leaves waiting approval','numeric',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Least work allocated peoples list' AND CompanyId = @CompanyId),'Id','uniqueidentifier',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Least work allocated peoples list' AND CompanyId = @CompanyId),'Employee name','nvarchar',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Least work allocated peoples list' AND CompanyId = @CompanyId),'Estimated time','varchar',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Least spent time employees' AND CompanyId = @CompanyId),'Id','uniqueidentifier',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Least spent time employees' AND CompanyId = @CompanyId),'Employee name','nvarchar',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Least spent time employees' AND CompanyId = @CompanyId),'Spent time','varchar',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Least spent time employees' AND CompanyId = @CompanyId),'Date','nvarchar',4)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Lates trend graph' AND CompanyId = @CompanyId),'Date','date',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Lates trend graph' AND CompanyId = @CompanyId),'MorningLateEmployeesCount','int',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Lates trend graph' AND CompanyId = @CompanyId),'AfternoonLateEmployee','int',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Items waiting for QA approval' AND CompanyId = @CompanyId),'Items waiting for QA approval','int',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Items deployed frequently' AND CompanyId = @CompanyId),'Items deployed frequently','int',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Intime trend graph' AND CompanyId = @CompanyId),'Date','date',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Intime trend graph' AND CompanyId = @CompanyId),'Morning late','int',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Highest replanned goals' AND CompanyId = @CompanyId),'Goal name','nvarchar',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Highest replanned goals' AND CompanyId = @CompanyId),'Replan count','int',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Highest replanned goals' AND CompanyId = @CompanyId),'Id','uniqueidentifier',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Highest bugs goals list' AND CompanyId = @CompanyId),'Id','uniqueidentifier',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Highest bugs goals list' AND CompanyId = @CompanyId),'Goal name','nvarchar',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Highest bugs goals list' AND CompanyId = @CompanyId),'Work items count','int',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Highest bugs goals list' AND CompanyId = @CompanyId),'Bugs count','int',4)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Goals vs Bugs count (p0, p1, p2)' AND CompanyId = @CompanyId),'Goal name','nvarchar',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Goals vs Bugs count (p0, p1, p2)' AND CompanyId = @CompanyId),'P0 bugs count','int',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Goals vs Bugs count (p0, p1, p2)' AND CompanyId = @CompanyId),'P1 bugs count','int',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Goals vs Bugs count (p0, p1, p2)' AND CompanyId = @CompanyId),'P2 bugs count','int',4)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Goals vs Bugs count (p0, p1, p2)' AND CompanyId = @CompanyId),'P3 bugs count','int',5)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Goals vs Bugs count (p0, p1, p2)' AND CompanyId = @CompanyId),'Total count','int',6)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Goals vs Bugs count (p0, p1, p2)' AND CompanyId = @CompanyId),'Id','uniqueidentifier',7)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Goals vs Bugs count (p0, p1, p2)' AND CompanyId = @CompanyId),'GoalName','nvarchar',8)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Goals not ontrack' AND CompanyId = @CompanyId),'Goals not ontrack','int',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Goal work items VS bugs count' AND CompanyId = @CompanyId),'Goal name','nvarchar',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Goal work items VS bugs count' AND CompanyId = @CompanyId),'Work items count','int',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Goal work items VS bugs count' AND CompanyId = @CompanyId),'Bugs count','int',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Goal work items VS bugs count' AND CompanyId = @CompanyId),'Id','uniqueidentifier',4)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Goal wise spent time VS productive hrs list' AND CompanyId = @CompanyId),'Id','uniqueidentifier',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Goal wise spent time VS productive hrs list' AND CompanyId = @CompanyId),'Goal name','nvarchar',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Goal wise spent time VS productive hrs list' AND CompanyId = @CompanyId),'Estimated time','varchar',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Goal wise spent time VS productive hrs list' AND CompanyId = @CompanyId),'Spent time','varchar',4)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Employee blocked work items/dependency analysis' AND CompanyId = @CompanyId),'Work item','nvarchar',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Employee blocked work items/dependency analysis' AND CompanyId = @CompanyId),'Owner name','nvarchar',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Employee blocked work items/dependency analysis' AND CompanyId = @CompanyId),'Dependency user','nvarchar',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Employee blocked work items/dependency analysis' AND CompanyId = @CompanyId),'Id','uniqueidentifier',4)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Employee assigned work items' AND CompanyId = @CompanyId),'Id','uniqueidentifier',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Employee assigned work items' AND CompanyId = @CompanyId),'UserStoryId','uniqueidentifier',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Employee assigned work items' AND CompanyId = @CompanyId),'GoalId','uniqueidentifier',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Employee assigned work items' AND CompanyId = @CompanyId),'SprintId','uniqueidentifier',4)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Employee assigned work items' AND CompanyId = @CompanyId),'Employee name','nvarchar',5)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Employee assigned work items' AND CompanyId = @CompanyId),'Work item','nvarchar',6)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Employee assigned work items' AND CompanyId = @CompanyId),'Goal name','nvarchar',7)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Employee assigned work items' AND CompanyId = @CompanyId),'Sprint name','nvarchar',8)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Dev wise deployed and bounce back stories count' AND CompanyId = @CompanyId),'Employee name','nvarchar',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Dev wise deployed and bounce back stories count' AND CompanyId = @CompanyId),'Id','uniqueidentifier',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Dev wise deployed and bounce back stories count' AND CompanyId = @CompanyId),'Deployed stories count','int',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Dev wise deployed and bounce back stories count' AND CompanyId = @CompanyId),'Bounced back count','int',4)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Dependency on me' AND CompanyId = @CompanyId),'UserStoryId','uniqueidentifier',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Dependency on me' AND CompanyId = @CompanyId),'GoalId','uniqueidentifier',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Dependency on me' AND CompanyId = @CompanyId),'SprintId','uniqueidentifier',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Dependency on me' AND CompanyId = @CompanyId),'Work item','nvarchar',4)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Dependency on me' AND CompanyId = @CompanyId),'Goal name','nvarchar',5)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Dependency on me' AND CompanyId = @CompanyId),'Sprint name','nvarchar',6)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Delayed work items' AND CompanyId = @CompanyId),'Work item','nvarchar',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Delayed work items' AND CompanyId = @CompanyId),'Id','uniqueidentifier',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Delayed work items' AND CompanyId = @CompanyId),'IsDateTimeConfiguration','bit',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Delayed work items' AND CompanyId = @CompanyId),'DeadLineDate','datetimeoffset',4)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Delayed goals' AND CompanyId = @CompanyId),'Goal name','nvarchar',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Delayed goals' AND CompanyId = @CompanyId),'Id','uniqueidentifier',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Delayed goals' AND CompanyId = @CompanyId),'Delayed by days','int',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Damaged assets' AND CompanyId = @CompanyId),'Damaged asssets','int',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Company productivity' AND CompanyId = @CompanyId),' This month company productivity ','int',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Company level productivity' AND CompanyId = @CompanyId),'Id','bigint',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Company level productivity' AND CompanyId = @CompanyId),'Month','nvarchar',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Company level productivity' AND CompanyId = @CompanyId),'Productivity','numeric',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Company level productivity' AND CompanyId = @CompanyId),'MonthDate','date',4)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Bugs list' AND CompanyId = @CompanyId),'Bug','nvarchar',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Bugs list' AND CompanyId = @CompanyId),'Goal name','nvarchar',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Bugs list' AND CompanyId = @CompanyId),'Sprint name','nvarchar',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Bugs list' AND CompanyId = @CompanyId),'Id','uniqueidentifier',4)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Bugs list' AND CompanyId = @CompanyId),'GoalId','uniqueidentifier',5)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Bugs list' AND CompanyId = @CompanyId),'SprintId','uniqueidentifier',6)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Bugs count on priority basis' AND CompanyId = @CompanyId),'StatusCount','nvarchar',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Bugs count on priority basis' AND CompanyId = @CompanyId),'StatusCounts','int',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Branch wise monthly productivity report' AND CompanyId = @CompanyId),'Id','uniqueidentifier',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Branch wise monthly productivity report' AND CompanyId = @CompanyId),'BranchName','nvarchar',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Branch wise monthly productivity report' AND CompanyId = @CompanyId),'Branch productivity','numeric',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Average Exit Time' AND CompanyId = @CompanyId),'Date','date',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Average Exit Time' AND CompanyId = @CompanyId),'Avg exit time','time',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All versions' AND CompanyId = @CompanyId),'Milestone name','nvarchar',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All versions' AND CompanyId = @CompanyId),'Id','uniqueidentifier',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All versions' AND CompanyId = @CompanyId),'Created on','datetime',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All versions' AND CompanyId = @CompanyId),'Blocked count','int',4)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All versions' AND CompanyId = @CompanyId),'Blocked percent','int',5)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All versions' AND CompanyId = @CompanyId),'Failed count','int',6)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All versions' AND CompanyId = @CompanyId),'Failed percent','int',7)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All versions' AND CompanyId = @CompanyId),'Passed count','int',8)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All versions' AND CompanyId = @CompanyId),'Passed percent','int',9)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All versions' AND CompanyId = @CompanyId),'Retest count','int',10)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All versions' AND CompanyId = @CompanyId),'Restest percent','int',11)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All versions' AND CompanyId = @CompanyId),'Untested count','int',12)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All versions' AND CompanyId = @CompanyId),'Untested percent','int',13)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All testruns ' AND CompanyId = @CompanyId),'Testrun name','nvarchar',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All testruns ' AND CompanyId = @CompanyId),'Id','uniqueidentifier',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All testruns ' AND CompanyId = @CompanyId),'Run date','datetime',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All testruns ' AND CompanyId = @CompanyId),'Blocked count','int',4)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All testruns ' AND CompanyId = @CompanyId),'Blocked percent','int',5)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All testruns ' AND CompanyId = @CompanyId),'Failed count','int',6)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All testruns ' AND CompanyId = @CompanyId),'Failed percent','int',7)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All testruns ' AND CompanyId = @CompanyId),'Passed count','int',8)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All testruns ' AND CompanyId = @CompanyId),'Passed percent','int',9)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All testruns ' AND CompanyId = @CompanyId),'Retest count','int',10)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All testruns ' AND CompanyId = @CompanyId),'Retest percent','int',11)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All testruns ' AND CompanyId = @CompanyId),'Untested count','int',12)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All testruns ' AND CompanyId = @CompanyId),'Untested percent','int',13)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All testruns ' AND CompanyId = @CompanyId),'P0 bugs','int',14)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All testruns ' AND CompanyId = @CompanyId),'P1 bugs','int',15)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All testruns ' AND CompanyId = @CompanyId),'P2 bugs','int',16)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All testruns ' AND CompanyId = @CompanyId),'P3 bugs','int',17)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All testruns ' AND CompanyId = @CompanyId),'Total bugs','int',18)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All test suites' AND CompanyId = @CompanyId),'Testsuite name','nvarchar',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All test suites' AND CompanyId = @CompanyId),'Estimate in hours','varchar',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All test suites' AND CompanyId = @CompanyId),'Cases count','int',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All test suites' AND CompanyId = @CompanyId),'Runs count','int',4)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All test suites' AND CompanyId = @CompanyId),'Created on','datetime',5)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All test suites' AND CompanyId = @CompanyId),'sections count','int',6)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All test suites' AND CompanyId = @CompanyId),'P0 bugs','int',7)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All test suites' AND CompanyId = @CompanyId),'P1 bugs','int',8)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All test suites' AND CompanyId = @CompanyId),'P2 bugs','int',9)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All test suites' AND CompanyId = @CompanyId),'P3 bugs','int',10)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All test suites' AND CompanyId = @CompanyId),'Total bugs count','int',11)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'All test suites' AND CompanyId = @CompanyId),'Id','uniqueidentifier',12)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Afternoon late employees' AND CompanyId = @CompanyId),'Date','nvarchar',1)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Afternoon late employees' AND CompanyId = @CompanyId),'Afternoon late employee','nvarchar',2)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Afternoon late employees' AND CompanyId = @CompanyId),'Id','uniqueidentifier',3)
,((SELECT Id FROM CustomWidgets WHERE CustomWidgetName = 'Actively running projects ' AND CompanyId = @CompanyId),'Actively Running Projects','int',1)
)
  AS SOURCE ( [CustomWidgetId], [ColumnName], [ColumnType],[Order])
  ON Target.[CustomWidgetId] = Source.[CustomWidgetId] AND Target.[ColumnName] = Source.[ColumnName] AND Target.[ColumnType] = Source.[ColumnType]
  WHEN MATCHED THEN
  UPDATE SET [CustomWidgetId] = SOURCE.[CustomWidgetId],
              [Order] = SOURCE.[Order];

END				