using System;

namespace Btrak.Models.Goals
{
    public class GoalSpReturnModel
    {
        public Guid? GoalId { get; set; }
        public Guid? ProjectId { get; set; }
        public string ProjectName { get; set; }
        public Guid? BoardTypeId { get; set; }
        public string BoardTypeName { get; set; }
        public string GoalUniqueName { get; set; }
        public string GoalName { get; set; }
        public decimal? GoalBudget { get; set; }
        public DateTimeOffset OnboardProcessDate { get; set; }
        public bool? IsLocked { get; set; }
        public string GoalShortName { get; set; }
        public DateTimeOffset? InActiveDateTime { get; set; }
        public Guid? GoalResponsibleUserId { get; set; }
        public string GoalResponsibleUserName { get; set; }
        public DateTimeOffset? CreatedDateTime { get; set; }
        public Guid CreatedByUserId { get; set; }
        public string CreatedUserName { get; set; }
        public DateTimeOffset? UpdatedDateTime { get; set; }
        public Guid? UpdatedByUserId { get; set; }
        public string UpdateUserName { get; set; }
        public int BugsCount { get; set; }
        public Guid? GoalStatusId { get; set; }
        public Guid? TestSuiteId { get; set; }
        public string TestSuiteName { get; set; }
        public string GoalStatusName { get; set; }
        public string GoalStatusColor { get; set; }
        public bool? IsProductiveBoard { get; set; }
        public Guid? ConsiderEstimatedHoursId { get; set; }
        public string ConsiderHourName { get; set; }
        public bool? IsToBeTracked { get; set; }
        public Guid? BoardTypeApiId { get; set; }
        public bool? IsBugBoard { get; set; }
        public bool? IsSuperAgileBoard { get; set; }
        public bool? IsDefault { get; set; }
        public string BoardTypeApiName { get; set; }
        public Guid? BoadTypeUiId { get; set; }
        public Guid? ConfigurationId { get; set; }
        public string ConfigurationTypeName { get; set; }
        public string Version { get; set; }
        public DateTimeOffset? ParkedDateTime { get; set; }
        public string UserStoriesXml { get; set; }
        public string BoardTypeUiName { get; set; }
        public string Tag { get; set; }
        public bool IsEnableTestRepo { get; set; }

        public string GoalResponsibleProfileImage { get; set; }
        public string ProfileImage { get; set; }
        public Guid? BoardTypeUiId { get; set; }
        public string OnboardDate { get; set; }
        public bool? IsApproved { get; set; }
        public bool? IsCompleted { get; set; }
        public string GoalsXml { get; set; }
        public string Features { get; set; }

        public string EntityFeaturesXml { get; set; }
        public Guid? WorkflowId { get; set; }
        public Guid? UserStoryId { get; set; }
        public string UserStoryName { get; set; }
        public decimal? EstimatedTime { get; set; }
        public DateTimeOffset? DeadLineDate { get; set; }
        public Guid? OwnerUserId { get; set; }
        public string OwnerName { get; set; }
        public string OwnerFirstName { get; set; }
        public string OwnerSurName { get; set; }
        public string OwnerEmail { get; set; }
        public string OwnerPassword { get; set; }
        public string OwnerProfileImage { get; set; }
        public Guid? ProjectResponsiblePersonId { get; set; }
        public bool? ProjectIsArchived { get; set; }
        public DateTimeOffset? ProjectArchivedDateTime { get; set; }
        public string ProjectStatusColor { get; set; }
        public DateTimeOffset? GoalArchivedDateTime { get; set; }
        public bool? GoalIsArchived { get; set; }
        public Guid? DependencyUserId { get; set; }
        public string DependencyName { get; set; }
        public string DependencyFirstName { get; set; }
        public string DependencySurName { get; set; }
        public string DependencyProfileImage { get; set; }
        public int? Order { get; set; }
        public Guid? UserStoryStatusId { get; set; }
        public string UserStoryStatusName { get; set; }
        public string UserStoryStatusColor { get; set; }
        public bool? UserStoryStatusIsArchived { get; set; }
        public DateTime? UserStoryStatusArchivedDateTime { get; set; }
        public DateTimeOffset? ActualDeadLineDate { get; set; }
        public DateTimeOffset? UserStoryArchivedDateTime { get; set; }
        public Guid? BugPriorityId { get; set; }
        public Guid? BugPriority { get; set; }
        public string BugPriorityColor { get; set; }
        public Guid? BugCausedUserId { get; set; }
        public string BugCausedUserName { get; set; }
        public string BugCausedUserFirstName { get; set; }
        public string BugCausedUserSurName { get; set; }
        public string BugCausedUserProfileImage { get; set; }
        public Guid? UserStoryTypeId { get; set; }
        public Guid? ProjectFeatureId { get; set; }
        public bool? IsWarning { get; set; }
        public byte[] TimeStamp { get; set; }
        public int TotalCount { get; set; }
        public int GoalRepalnCount { get; set; }
        public int ActiveGoalsCount { get; set; }
        public int BackLogGoalsCount { get; set; }
        public bool? IsSprintsConfiguration { get; set; }
        public int UnderReplanGoalsCount { get; set; }
        public int ActiveUserStoryCount { get; set; }
        public DateTimeOffset? GoalDeadLine { get; set; }
        public decimal? GoalEstimatedTime { get; set; }
        public string Description { get; set; }
        public bool IsDateTimeConfiguration { get; set; }
        public DateTimeOffset? EndDate { get; set; }
        public decimal? GoalEstimateTime { get; set; }
    }
}
