CREATE TABLE [dbo].[ApiScopeClaims]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Type] NVARCHAR(250) NOT NULL,
	ScopeId INT NOT NULL,
	CONSTRAINT [PK_ApiScopeClaims] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON),
)
GO

ALTER TABLE [dbo].[ApiScopeClaims]  WITH NOCHECK ADD  CONSTRAINT [FK_ApiScopeClaims_ApiScopes_ScopeId] FOREIGN KEY([ScopeId])
REFERENCES [dbo].[ApiScopes] ([Id])
GO
