CREATE TABLE [dbo].[ApiScopeProperties]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Key] NVARCHAR(250) NOT NULL,
	[Value] NVARCHAR(250) NOT NULL,
	ScopeId INT NOT NULL,
	CONSTRAINT [PK_ApiScopeProperties] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON),
)
GO

ALTER TABLE [dbo].[ApiScopeProperties]  WITH NOCHECK ADD  CONSTRAINT [FK_ApiScopeProperties_ApiScopes_ScopeId] FOREIGN KEY([ScopeId])
REFERENCES [dbo].[ApiScopes] ([Id])
GO
