CREATE TABLE [dbo].[ClientScopes]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	Scope NVARCHAR(250),
	ClientId INT NOT NULL,
	CONSTRAINT [PK_ClientScopes] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON), 
)
GO

ALTER TABLE [dbo].[ClientScopes]  WITH NOCHECK ADD  CONSTRAINT [FK_ClientScopes_Clients_ClientId] FOREIGN KEY([ClientId])
REFERENCES [dbo].[Clients] ([Id])
GO