CREATE TABLE [dbo].[ClientClaims]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Type] NVARCHAR(250) NOT NULL,
	[Value] NVARCHAR(250) NOT NULL,
	ClientId INT NOT NULL,
	CONSTRAINT [PK_ClientClaims] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON), 
)
GO

ALTER TABLE [dbo].[ClientClaims]  WITH NOCHECK ADD  CONSTRAINT [FK_ClientClaims_Clients_ClientId] FOREIGN KEY([ClientId])
REFERENCES [dbo].[Clients] ([Id])
GO