CREATE TABLE [dbo].[ClientGrantTypes]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	GrantType NVARCHAR(250) NOT NULL,
	ClientId INT NOT NULL,
	CONSTRAINT [PK_ClientGrantTypes] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON), 
)
GO

ALTER TABLE [dbo].[ClientGrantTypes]  WITH NOCHECK ADD  CONSTRAINT [FK_ClientGrantTypes_Clients_ClientId] FOREIGN KEY([ClientId])
REFERENCES [dbo].[Clients] ([Id])
GO