CREATE TABLE [dbo].[AuditQuestionVersions]
(
	[Id] [uniqueidentifier] NOT NULL,
	[AuditComplianceVersionId] [uniqueidentifier] NOT NULL,
	[QuestionName] [nvarchar](800) NULL,
	[QuestionDescription] [nvarchar](MAX) NULL,
	[QuestionTypeId] [uniqueidentifier] NOT NULL,
	[AuditCategoryId] [uniqueidentifier] NULL,
	[QuestionResponsiblePersonId] [uniqueidentifier] NULL,
	[QuestionResult] [nvarchar](800) NULL,
	[Order] INT NULL,
	[EstimatedTime] [decimal](18, 2) NULL,
	[CreatedDateTime] [datetime] NOT NULL,
    [CreatedByUserId] [uniqueidentifier] NOT NULL,
    [InActiveDateTime] [datetime] NULL,
	[PriorityId] UNIQUEIDENTIFIER NULL,
	[ImpactId] UNIQUEIDENTIFIER NULL,
	[RiskId] UNIQUEIDENTIFIER NULL,
	[CompanyId] UNIQUEIDENTIFIER NULL,
	[QuestionIdentity] NVARCHAR(25) NULL,
	[IsMandatory] BIT NULL,
	[IsOriginalQuestionTypeScore] BIT NULL, 
    [QuestionHint] NVARCHAR(MAX) NULL, 
)
