CREATE TABLE [dbo].[AuditConductQuestions]
(
    [Id] [uniqueidentifier] NOT NULL,
    [QuestionId] UNIQUEIDENTIFIER,
    [AuditConductId] [uniqueidentifier] NULL,
    [QuestionName] [nvarchar](800) NULL,
    [QuestionDescription] [nvarchar](MAX) NULL,
    [QuestionTypeId] [uniqueidentifier] NOT NULL,
    [QuestionTypeName] NVARCHAR(MAX),
    [AuditCategoryId] [uniqueidentifier] NULL,
    [QuestionResponsiblePersonId] [uniqueidentifier] NULL,
    [QuestionResult] [nvarchar](800) NULL,
    [Order] INT   NULL,
    [PriorityId] UNIQUEIDENTIFIER NULL,
	[ImpactId] UNIQUEIDENTIFIER NULL,
	[RiskId] UNIQUEIDENTIFIER NULL,
    [EstimatedTime] [decimal](18, 2) NULL,
    [CreatedDateTime] [datetime] NOT NULL,
    [CreatedByUserId] [uniqueidentifier] NOT NULL,
    [InActiveDateTime] [datetime] NULL,
    [UpdatedDateTime] [datetime] NULL,
    [UpdatedByUserId] [uniqueidentifier] NULL,
    [TimeStamp] TIMESTAMP,
    [CompanyId] UNIQUEIDENTIFIER NULL,
    [QuestionIdentity] NVARCHAR(25) NULL,
    [IsMandatory] BIT NULL,
    [MasterQuestionTypeId] UNIQUEIDENTIFIER,
    [QuestionHint] NVARCHAR(MAX) NULL,
    CONSTRAINT [PK_AuditConductQuestions] PRIMARY KEY ([Id]), 
    CONSTRAINT [FK_AuditConductQuestions_AuditQuestions] FOREIGN KEY ([QuestionId]) REFERENCES [AuditQuestions]([Id]), 
    CONSTRAINT [FK_AuditConductQuestions_AuditConduct] FOREIGN KEY ([AuditConductId]) REFERENCES [AuditConduct]([Id]), 
    CONSTRAINT [FK_AuditConductQuestions_ToTable_1] FOREIGN KEY ([QuestionTypeId]) REFERENCES [QuestionTypes]([Id])
)