CREATE TABLE [dbo].[CreditNotes]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	SiteId UNIQUEIDENTIFIER NOT NULL,
	GrdId UNIQUEIDENTIFIER NULL,
	[Month] DATETIME NULL,
	StartDate DATETIME NULL,
	EndDate DATETIME NULL,
	EntryDate DATETIME NULL,
	Term NVARCHAR(20) NULL,
	[Name] NVARCHAR(250) NULL,
	[InvoiceUrl] NVARCHAR(MAX) NULL,
	[Year] DATETIME NULL,
	[IsTVAApplied] BIT NULL,
	[IsGenerateInvoice] BIT NULL,
	[TVA] DECIMAL(18,2) NULL,
	CompanyId UNIQUEIDENTIFIER NOT NULL,
	CreatedByUserId UNIQUEIDENTIFIER NOT NULL,
	CreatedDateTime DATETIME NOT NULL,
	UpdatedByUserId UNIQUEIDENTIFIER NULL,
	UpdatedDateTime DATETIME NULL,
	[InActiveDateTime] DATETIME NULL,
	[TimeStamp] TIMESTAMP
 CONSTRAINT [PK_CreditNotes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY], 
)
GO