CREATE TABLE [dbo].[CustomFieldHistory]
(
	[Id] UNIQUEIDENTIFIER NOT NULL , 
    [CustomFieldId] UNIQUEIDENTIFIER NULL, 
    [ReferenceId] UNIQUEIDENTIFIER NULL, 
	[ReferenceTypeId] UNIQUEIDENTIFIER NULL, 
    [OldValue] NVARCHAR(MAX) NULL, 
    [NewValue] NVARCHAR(MAX) NULL, 
    [CreatedByUserId] UNIQUEIDENTIFIER NULL, 
    [CreatedDateTime] DATETIMEOFFSET NULL, 
    [UpdatedByUserId] UNIQUEIDENTIFIER NULL, 
    [UpdatedDateTime] DATETIME NULL, 
    [Description] NVARCHAR(MAX) NULL, 
    [TimeStamp] TIMESTAMP NOT NULL
CONSTRAINT [PK_CustomFieldHistory] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY], 
    [CreatedDateTimeZoneId] UNIQUEIDENTIFIER NULL
) ON [PRIMARY]
GO