CREATE TABLE [dbo].[EncashmentType]
(
	[Id] UNIQUEIDENTIFIER NOT NULL, 
    [EncashmentType] NVARCHAR(100) NULL, 
	[CompanyId] UNIQUEIDENTIFIER NULL,
    [CreatedDateTime] DATETIME NOT NULL, 
    [CreatedByUserId] UNIQUEIDENTIFIER NOT NULL, 
	[UpdatedByUserId] UNIQUEIDENTIFIER NULL,
	[UpdatedDateTime] DATETIME NULL,
    [InActiveDateTime] DATETIME NULL, 			 
	[TimeStamp] TIMESTAMP NULL, 
    CONSTRAINT [PK_EncashmentTypes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON), 
)
GO
