CREATE TABLE [dbo].[EntryFormField]
(
	[Id] UNIQUEIDENTIFIER NOT NULL , 
    [DisplayName] NVARCHAR(250) NOT NULL, 
    [FieldName] NVARCHAR(250) NOT NULL, 
    [IsDisplay] BIT NULL, 
    [CompanyId] UNIQUEIDENTIFIER NOT NULL, 
    [CreatedDateTime] DATETIME NULL, 
    [CreatedByUserId] UNIQUEIDENTIFIER NULL, 
    [UpdatedDateTime] DATETIME NULL, 
    [UpdatedByUserId] UNIQUEIDENTIFIER NULL, 
    [InActiveDateTime] DATETIME NULL
CONSTRAINT [PK_EntryFormField] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON), 
    [TimeStamp] TIMESTAMP NULL, 
    [Unit] NVARCHAR(50) NULL, 
    [FieldTypeId] UNIQUEIDENTIFIER NULL, 
    [GRDId] UNIQUEIDENTIFIER NULL, 
    [SelectedGrdIds] NVARCHAR(MAX) NULL, 
   
)
GO
