CREATE TABLE [dbo].[ExpectedProductiveHours]
(
	Id UNIQUEIDENTIFIER NOT NULL,
	UserId UNIQUEIDENTIFIER NOT NULL,
	FromDate DATETIME NULL,
	ToDate DATETIME NULL,
	[Hours] Decimal NOT NULL,
	CreatedDateTime DateTime NULL,
	CreatedByUserId UNIQUEIDENTIFIER NULL,
	[CompanyId] UNIQUEIDENTIFIER NULL, 
	[InActiveDateTime] [datetime] NULL,
	[TimeStamp] TIMESTAMP,
CONSTRAINT [PK_ExpectedProductiveHours] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO