CREATE TABLE [dbo].[ExpenseReport] (
    [Id]                           UNIQUEIDENTIFIER NOT NULL,
    [ReportTitle]                  NVARCHAR (200)   NOT NULL,
    [BusinessPurpose]              NVARCHAR (500)   NOT NULL,
    [DurationFrom]                 DATE             NOT NULL,
    [DurationTo]                   DATE             NOT NULL,
    [ReportStatusId]               UNIQUEIDENTIFIER NOT NULL,
    [AdvancePayment]               FLOAT (53)       NULL,
    [AmountToBeReimbursed]         FLOAT (53)       NULL,
    [IsReimbursed]                 BIT              NOT NULL,
    [UndoReimbursement]            BIT              NOT NULL,
    [IsApproved]                   BIT              NULL,
    [CreatedByUserId]              UNIQUEIDENTIFIER NOT NULL,
    [CreatedDateTime]              DATETIME         NOT NULL,
    [SubmittedByUserId]            UNIQUEIDENTIFIER NULL,
    [SubmittedDateTime]            DATETIME         NULL,
    [ReimbursedByUserId]           UNIQUEIDENTIFIER NULL,
    [ReimbursedDateTime]           DATETIME         NULL,
    [ReasonForApprovalOrRejection] NVARCHAR (500)   NULL,
    [ApprovedOrRejectedByUserId]   UNIQUEIDENTIFIER NULL,
    [ApprovedOrRejectedDateTime]   DATETIME         NULL,
    [InActiveDateTime] [datetime] NULL,
    [TimeStamp] TIMESTAMP NULL,
    CONSTRAINT [PK_ExpenseReport] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ExpenseReport_ApprovedUser] FOREIGN KEY ([ApprovedOrRejectedByUserId]) REFERENCES [dbo].[User] ([Id]),
    CONSTRAINT [FK_ExpenseReport_ExpenseReportStatus] FOREIGN KEY ([ReportStatusId]) REFERENCES [dbo].[ExpenseReportStatus] ([Id]),
    CONSTRAINT [FK_ExpenseReport_ReimbursedUser] FOREIGN KEY ([ReimbursedByUserId]) REFERENCES [dbo].[User] ([Id]),
    CONSTRAINT [FK_ExpenseReport_SubmittedUser] FOREIGN KEY ([SubmittedByUserId]) REFERENCES [dbo].[User] ([Id]),
    CONSTRAINT [FK_ExpenseReport_User] FOREIGN KEY ([CreatedByUserId]) REFERENCES [dbo].[User] ([Id]),
)
GO