CREATE TABLE [dbo].[GoalFilter]
(
	[Id] UNIQUEIDENTIFIER NOT NULL , 
    [GoalFilterName] NVARCHAR(50) NULL, 
    [IsPublic] BIT NULL, 
    [CreatedDateTime] DATETIME NULL, 
    [CreatedByUserId] UNIQUEIDENTIFIER NULL, 
    [UpdatedDateTime] DATETIME NULL, 
    [UpdatedByUserId] UNIQUEIDENTIFIER NULL CONSTRAINT [PK_GoalFilter] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON), 
    [InActiveDateTime] DATETIME NULL, 
)
GO