CREATE TABLE [dbo].[GRD]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	StartDate DATETIME NOT NULL,
	EndDate DATETIME NOT NULL,
	[Name] NVARCHAR(250) NOT NULL,
	RepriseTariff DECIMAL(18, 2) NOT NULL,
	AutoCTariff DECIMAL(18, 2) NULL,
	CompanyId UNIQUEIDENTIFIER NOT NULL,
	CreatedByUserId UNIQUEIDENTIFIER NOT NULL,
	CreatedDateTime DATETIME NOT NULL,
	UpdatedByUserId UNIQUEIDENTIFIER NULL,
	UpdatedDateTime DATETIME NULL,
	[InActiveDateTime] DATETIME NULL,
	[TimeStamp] TIMESTAMP
 CONSTRAINT [PK_GRD] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY], 
) ON [PRIMARY]
GO
