CREATE TABLE [dbo].[LeadTemplates]
(
	[Id] UNIQUEIDENTIFIER NOT NULL , 
    [FormName] NVARCHAR(250) NULL, 
    [FormJson] NVARCHAR(MAX) NULL, 
    [CreatedDateTime] DATETIME NULL, 
    [CreatedByUserId] UNIQUEIDENTIFIER NULL, 
    [UpdatedDateTime] DATETIME NULL, 
    [UpdatedByUserId] UNIQUEIDENTIFIER NULL, 
    [InActiveDateTime] DATETIME NULL, 
    [TimeStamp] TIMESTAMP NULL
, 
    [CompanyId] UNIQUEIDENTIFIER NULL, 
  CONSTRAINT [PK_LeadTemplates] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO
