CREATE TABLE [dbo].[LeadContactSubmissions]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [UniqueLeadId] NVARCHAR(250) NOT NULL,
    [SalesPersonId] UNIQUEIDENTIFIER NOT NULL,  
    [LeadDate] DATETIME NOT NULL,
    [ContractId] UNIQUEIDENTIFIER NULL, 
    [ClientId] UNIQUEIDENTIFIER NOT NULL,
    [ProductId] UNIQUEIDENTIFIER NOT NULL,
    [GradeId] UNIQUEIDENTIFIER NOT NULL,
    [QuantityInMT] DECIMAL(18,3) NOT NULL,
    [RateGST] DECIMAL(18,3) NULL,
    [PaymentTypeId] UNIQUEIDENTIFIER NULL,
    [VehicleNumberOfTransporter] NVARCHAR(250) NULL,
    [MobileNumberOfTruckDriver] NVARCHAR(250) NULL,
    [Drums] Int NULL,
    [PortId] UNIQUEIDENTIFIER NULL,
    [IsClosed] BIT NULL,
    [BLNumber] NVARCHAR(250) NULL,
    [ExceptionApprovalRequired] BIT NULL,
    [StatusId] UNIQUEIDENTIFIER NOT NULL, 
    [ShipmentMonth] DATETIME NULL,
    [CountryOriginId] UNIQUEIDENTIFIER NULL, 
    [TermsOfDelivery] NVARCHAR(MAX) NULL,
    [CustomPoint] NVARCHAR(MAX) NULL,
    [CreatedByUserId] UNIQUEIDENTIFIER NOT NULL, 
    [CompanyId] UNIQUEIDENTIFIER NOT NULL, 
    [UpdatedByUserId] UNIQUEIDENTIFIER NULL, 
    [CreatedDateTime] DATETIME NOT NULL, 
    [UpdatedDateTime] DATETIME NULL, 
    [InActiveDateTime] DATETIME NULL,
    [TimeStamp] TIMESTAMP, 
    [FinalVehicleNumberOfTransporter] NVARCHAR(50) NULL, 
    [FinalMobileNumberOfTruckDriver] NVARCHAR(50) NULL, 
    [FinalQuantityInMT] DECIMAL(18,3) NULL, 
    [FinalDrums] INT NULL, 
    [FinalPortId] UNIQUEIDENTIFIER NULL, 
    [FinalBLNumber] NVARCHAR(250) NULL, 
    [WeighingSlipNumber] NVARCHAR(50) NULL, 
    [WeighingSlipDate] DATETIME NULL, 
    [WeighingSlipPhoto] NVARCHAR(MAX) NULL, 
    [UploadedOther] NVARCHAR(MAX) NULL, 
    [WhUpdatedUserId] UNIQUEIDENTIFIER NULL, 
    [WhUpdatedDateTime] DATETIME NULL, 
    [InvoiceNumber] NVARCHAR(50) NULL, 
    [DeliveryNote] NVARCHAR(50) NULL, 
    [SuppliersRef] NVARCHAR(50) NULL
)
