CREATE TABLE [dbo].[LinkUserStoryType]
(
	[Id] UNIQUEIDENTIFIER NOT NULL, 
    [LinkUserStoryTypeName] NVARCHAR(50) NULL, 
    [CreatedDateTime] DATETIME NULL, 
    [CreatedByUserId] UNIQUEIDENTIFIER NULL, 
    [UpdatedDateTime] DATETIME NULL, 
    [UpdatedByUserId] UNIQUEIDENTIFIER NULL, 
    [InActiveDateTime] DATETIME NULL, 
    [CompanyId] UNIQUEIDENTIFIER NULL,
    [TimeStamp] TIMESTAMP NOT NULL
CONSTRAINT [PK_LinkUserStoryType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON), 
)
GO