CREATE TABLE [dbo].[MemberShip]
(
	[Id] UNIQUEIDENTIFIER NOT NULL , 
    [MemberShipType] NVARCHAR(50) NULL, 
    [CompanyId] UNIQUEIDENTIFIER NULL, 
    [CreatedDateTime] DATETIME NOT NULL, 
    [CreatedByUserId] UNIQUEIDENTIFIER NOT NULL, 
	[UpdatedDateTime]  DATETIME          NULL,
    [UpdatedByUserId]  UNIQUEIDENTIFIER  NULL,
    [InactiveDateTime] DATETIME NULL, 
    [TimeStamp] TIMESTAMP NOT NULL,
 CONSTRAINT [PK_MemberShip] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON), 
)
GO