CREATE TABLE [dbo].[MessageFieldMaster]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	MessageType NVARCHAR(250) NOT NULL,
	DisplayText NVARCHAR(250) NOT NULL,
	GrdId UNIQUEIDENTIFIER NULL,
	IsDisplay BIT DEFAULT 0,
	CompanyId UNIQUEIDENTIFIER NOT NULL,
	CreatedByUserId UNIQUEIDENTIFIER NOT NULL,
	CreatedDateTime DATETIME NOT NULL,
	UpdatedByUserId UNIQUEIDENTIFIER NULL,
	UpdatedDateTime DATETIME NULL,
	[InActiveDateTime] DATETIME NULL,
	[TimeStamp] TIMESTAMP
 CONSTRAINT [PK_MessageFieldMaster] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY], 
    [SelectedGrdIds] NVARCHAR(MAX) NULL, 
) ON [PRIMARY]
GO

GO
