CREATE TABLE [dbo].[PaymentReceipt]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	EntryDate DATETIME NULL,
	[Month] DATETIME NULL,
	[Year] DATETIME NULL,
	Term NVARCHAR(20) NULL,
	SiteId UNIQUEIDENTIFIER NOT NULL,
	BankReceiptDate DATETIME NOT NULL,
	BankReference NVARCHAR(250) NOT NULL,
	BankId UNIQUEIDENTIFIER NOT NULL,
	Comments NVARCHAR(250) NULL,
	PayValue DECIMAL(18,2) NOT NULL,
	CompanyId UNIQUEIDENTIFIER NOT NULL,
	CreatedByUserId UNIQUEIDENTIFIER NOT NULL,
	CreatedDateTime DATETIME NOT NULL,
	UpdatedByUserId UNIQUEIDENTIFIER NULL,
	UpdatedDateTime DATETIME NULL,
	[InActiveDateTime] DATETIME NULL,
	[TimeStamp] TIMESTAMP
 CONSTRAINT [PK_PaymentReceipt] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY], 
)
GO