CREATE TABLE [dbo].[PaymentReceiptEntryForms]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[PaymentReceiptId] UNIQUEIDENTIFIER NOT NULL,
	[EntryFormId] UNIQUEIDENTIFIER NOT NULL,
	[InactiveDateTime] DATETIME NULL, 
	CreatedDateTime DATETIME NOT NULL,
    CreatedByUserId UNIQUEIDENTIFIER NOT NULL,
	[UpdatedDateTime] DATETIME NULL,
    [UpdatedByUserId] UNIQUEIDENTIFIER NULL,
	CONSTRAINT [PK_PaymentReceiptEntryForms] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON), 
   
)
GO
