CREATE TABLE [dbo].[PeakHour]
(
	[Id] UNIQUEIDENTIFIER NOT NULL, 
	[CompanyId] [uniqueidentifier] NULL,
    [PeakHourOn] NVARCHAR(250) NOT NULL,
	[FilterType] NVARCHAR(250) NULL,
	[IsPeakHour] BIT NULL,
	[PeakHourFrom] TIME NOT NULL,
	[PeakHourTo] TIME NOT NULL,
	[CreatedDateTime] [datetime] NOT NULL,
	[CreatedByUserId] [uniqueidentifier] NOT NULL,
	[UpdatedDateTime]  DATETIME          NULL,
    [UpdatedByUserId]  UNIQUEIDENTIFIER  NULL,
	[InActiveDateTime] [datetime] NULL,
	[TimeStamp] TIMESTAMP
CONSTRAINT [PK_PeakHour] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON), 
)
GO

CREATE NONCLUSTERED INDEX IX_PeakHour_CompanyId 
ON [dbo].[PeakHour] (  CompanyId ASC  )   
WITH (  PAD_INDEX = OFF ,FILLFACTOR = 80   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , DROP_EXISTING = ON , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  ) 
ON [PRIMARY]
GO
