CREATE TABLE [dbo].[ProductivityDataPoints]
(
	Id UNIQUEIDENTIFIER NOT NULL,
	UserId UNIQUEIDENTIFIER NOT NULL,
	[Hours] Decimal NULL,
	CreatedDateTime DateTime NULL,
	CreatedByUserId UNIQUEIDENTIFIER NULL,
	[CompanyId] UNIQUEIDENTIFIER NULL 
CONSTRAINT [PK_ProductivityDataPoints] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO
