CREATE TABLE [dbo].[PurchaseContracts]
(
	[Id] [uniqueidentifier] NOT NULL PRIMARY KEY,
	CompanyId [uniqueidentifier]  NULL,
	[ClientId] [uniqueidentifier]  NULL,
    [ContractNumber] NVARCHAR(200) NULL,
	[StartDate] [date] NULL,
	[EndDate] [date] NULL, 
	[ProductId] [uniqueidentifier]  NULL,
	[GradeId] [uniqueidentifier]  NULL,
	[Price] Decimal(18,2) null,
	[TotalQuantity] [int] null,
	[UsedQuantity] [int] null,
	[RemaningQuantity] [int] null,
	[UniqueName] [nvarchar](250) NULL,
	[Description] NVARCHAR(250) NULL, 
	[ContractDocument] NVARCHAR(MAX) NULL, 
    [InactiveDateTime] DATETIME NULL, 
	[TimeStamp] TIMESTAMP,
	[CreatedDateTime] [datetime] NOT NULL,
	[CreatedByUserId] [uniqueidentifier] NOT NULL,
	[UpdatedDateTime] [datetime] NULL,
	[UpdatedByUserId] [uniqueidentifier] NULL,
)
