CREATE TABLE [dbo].[PurchaseShipmentBLs]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	PurchaseExecutionId UNIQUEIDENTIFIER NOT NULL,
	BLNumber NVARCHAR(250) NULL,
	BLDate Date NULL,
	BLQuantity DECIMAL(18,2),
	ConsignerId UNIQUEIDENTIFIER NULL,
	ConsigneeId UNIQUEIDENTIFIER NULL,
	ChaId UNIQUEIDENTIFIER NULL,
	NotifyParty NVARCHAR(250) NULL,
	PackingDetails NVARCHAR(250) NULL,
	IsDocumentsSent BIT NULL,
	SentDate DATE NULL,
	DraftEntryDate DATE NULL,
	DraftBLNumber NVARCHAR(250) NULL,
	DraftBLDescription NVARCHAR(250) NULL,
	DraftBasicCustomsDuty NVARCHAR(250) NULL,
	DraftSWC DECIMAL(18,2) NULL,
	DraftIGST DECIMAL(18,2) NULL,
	DraftEduCess DECIMAL(18,2) NULL,
	DraftOthers DECIMAL(18,2) NULL,
	ConfoEntryDate DATE NULL,
	ConfoBLNumber NVARCHAR(250) NULL,
	ConfoBLDescription NVARCHAR(250) NULL,
	ConfoBasicCustomsDuty NVARCHAR(250) NULL,
	ConfoSWC DECIMAL(18,2) NULL,
	ConfoIGST DECIMAL(18,2) NULL,
	ConfoEduCess DECIMAL(18,2) NULL,
	ConfoOthers DECIMAL(18,2) NULL,
	IsConfirmedBill BIT NULL,
	ConfirmationDate DATE NULL,
	ConfoIsPaymentDone BIT NULL,
	ConfoPaymentDate DATE NULL,
	CompanyId [uniqueidentifier]  NULL,
    [InactiveDateTime] DATETIME NULL, 
	[TimeStamp] TIMESTAMP,
	[CreatedDateTime] [datetime] NOT NULL,
	[CreatedByUserId] [uniqueidentifier] NOT NULL,
	[UpdatedDateTime] [datetime] NULL,
    [UpdatedDateTimeZone] [uniqueidentifier] NULL,
	[UpdatedByUserId] [uniqueidentifier] NULL
)
