CREATE TABLE [dbo].[RFQRequest]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	ClientId UNIQUEIDENTIFIER NOT NULL,
	DataSourceId UNIQUEIDENTIFIER,
	CreatedDateTime DATETIME NOT NULL,
	CreatedByUserId UNIQUEIDENTIFIER NOT NULL,
	UpdatedDateTime DATETIME NULL,
	UpdatedByUserId UNIQUEIDENTIFIER NULL,
	InActiveDatetime DATETIME NULL,
	[TimeStamp] TIMESTAMP
)
