CREATE TABLE [dbo].[RosterActualPlan]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[RequestId] UNIQUEIDENTIFIER NOT NULL,
	[SolutionId] UNIQUEIDENTIFIER NOT NULL,
	[PlanDate] DATETIME NOT NULL,
	[DepartmentId] UNIQUEIDENTIFIER NULL,
	[ShiftId] UNIQUEIDENTIFIER NULL,
	[CurrencyCode] UNIQUEIDENTIFIER NULL,
	[PlannedEmployeeId] UNIQUEIDENTIFIER NULL,
	[PlannedRate] DECIMAL(14,2) NULL,
	[PlannedFromTime] Time NULL,
	[PlannedToTime] Time NULL,
	[ActualEmployeeId] UNIQUEIDENTIFIER NULL,
	[ActualRate] DECIMAL(14,2) NULL,
	[ActualFromTime] Time NULL,
	[ActualToTime] Time NULL,
	[PlanStatusId] UNIQUEIDENTIFIER NOT NULL,
	[CompanyId] UNIQUEIDENTIFIER NULL,
	[CreatedDateTime] DATETIME NOT NULL,
	[CreatedByUserId] UNIQUEIDENTIFIER NOT NULL,
	[InActiveDateTime] DATETIME NULL,
	[UpdatedDateTime] DATETIME NULL,
    [UpdatedByUserId] UNIQUEIDENTIFIER NULL,
	[TimeStamp] TimeStamp NOT NULL

CONSTRAINT [PK_RosterActualPlan] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON), 
)
GO

CREATE NONCLUSTERED INDEX IX_RosterActualPlan_CompanyId 
ON [dbo].[RosterActualPlan] (  CompanyId ASC  )   
WITH (  PAD_INDEX = OFF ,FILLFACTOR = 80   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , DROP_EXISTING = ON , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  ) 
ON [PRIMARY]
