CREATE TABLE [dbo].[RosterPlanStatus]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[StatusName] NVARCHAR(150) NOT NULL,
	[StatusOrder] INT NOT NULL,
	[StatusColor] VARCHAR(15),
	[CompanyId] UNIQUEIDENTIFIER NULL,
	[CreatedDateTime] DATETIME NOT NULL,
	[CreatedByUserId] UNIQUEIDENTIFIER NOT NULL,
	[InActiveDateTime] DATETIME NULL,
	[UpdatedDateTime] DATETIME NULL,
    [UpdatedByUserId] UNIQUEIDENTIFIER NULL,
	[TimeStamp] TimeStamp NOT NULL

CONSTRAINT [PK_RosterPlanStatus] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON), 
)
GO