CREATE TABLE [dbo].[RosterSolution]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[RequestId] UNIQUEIDENTIFIER NOT NULL,
	[SolutionName] NVARCHAR(150) NULL,
	[BudgetAllocated] INT NULL,
	[CompanyId] UNIQUEIDENTIFIER NULL,
	[CreatedDateTime] DATETIME NOT NULL,
	[CreatedByUserId] UNIQUEIDENTIFIER NOT NULL,
	[InActiveDateTime] DATETIME NULL,
	[UpdatedDateTime] DATETIME NULL,
    [UpdatedByUserId] UNIQUEIDENTIFIER NULL,
	[TimeStamp] TimeStamp NOT NULL

CONSTRAINT [PK_RosterSolution] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON), 
)
GO

CREATE NONCLUSTERED INDEX IX_RosterSuggestedPlans_CompanyId 
ON [dbo].[RosterSolution] (  CompanyId ASC  )   
WITH (  PAD_INDEX = OFF ,FILLFACTOR = 80   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , DROP_EXISTING = ON , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  ) 
ON [PRIMARY]

