CREATE TABLE [dbo].[SoftLabelConfigurations]
(
	[Id] UNIQUEIDENTIFIER NOT NULL , 
    [ProjectLabel] NVARCHAR(50) NOT NULL, 
    [GoalLabel] NVARCHAR(50) NOT NULL, 
    [UserStoryLabel] NVARCHAR(50) NOT NULL, 
	[AuditLabel] NVARCHAR(50)  NULL,
	[AuditsLabel] NVARCHAR(50)  NULL,
	[ConductLabel] NVARCHAR(50)  NULL,
	[ConductsLabel] NVARCHAR(50)  NULL,
	[ActionLabel] NVARCHAR(50)  NULL,
	[ActionsLabel] NVARCHAR(50)  NULL,
	[TimelineLabel] NVARCHAR(50)  NULL,
	[AuditReportLabel] NVARCHAR(50)  NULL,
	[AuditReportsLabel] NVARCHAR(50)  NULL,
	[ReportLabel] NVARCHAR(50)  NULL,
	[ReportsLabel] NVARCHAR(50)  NULL,
	[AuditActivityLabel] NVARCHAR(50)  NULL,
	[AuditAnalyticsLabel] NVARCHAR(50)  NULL,
	[AuditQuestionLabel] NVARCHAR(50) NULL,
	[AuditQuestionsLabel] NVARCHAR(50) NULL,
    [CompanyId] UNIQUEIDENTIFIER NOT NULL, 
    [CreatedDateTime] DATETIME NULL, 
    [CreatedByUserId] UNIQUEIDENTIFIER NULL, 
    [UpdatedDateTime] DATETIME NULL, 
    [UpdatedByUserId] UNIQUEIDENTIFIER NULL, 
    [timestamp] TIMESTAMP NOT NULL
 CONSTRAINT [PK_SoftLabelConfigurations] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON), 
    [InActiveDateTime] DATETIME NULL, 
    [EmployeeLabel] NVARCHAR(50) NULL, 
    [DeadlineLabel] NVARCHAR(50) NULL, 
    [ProjectsLabel] NVARCHAR(50) NULL, 
    [GoalsLabel] NVARCHAR(50) NULL, 
    [EmployeesLabel] NVARCHAR(50) NULL, 
    [UserStoriesLabel] NVARCHAR(50) NULL, 
    [DeadlinesLabel] NVARCHAR(50) NULL,
	[ScenarioLabel] NVARCHAR(50) NULL,
    [ScenariosLabel] NVARCHAR(50) NULL,
    [RunLabel] NVARCHAR(50) NULL,
    [RunsLabel] NVARCHAR(50) NULL,
    [VersionLabel] NVARCHAR(50) NULL,
    [VersionsLabel] NVARCHAR(50) NULL,
    [TestReportLabel] NVARCHAR(50) NULL,
    [TestReportsLabel] NVARCHAR(50) NULL,
	[EstimatedTimeLabel] NVARCHAR(50) NULL, 
    [EstimationLabel] NVARCHAR(50) NULL, 
    [EstimationsLabel] NVARCHAR(50) NULL,
    [EstimateLabel] NVARCHAR(50) NULL,
    [EstimatesLabel] NVARCHAR(50) NULL, 
    [ClientLabel] NVARCHAR(50) NULL, 
    [ClientsLabel] NVARCHAR(50) NULL
)
