CREATE TABLE [dbo].[SolarLogForm]
(
	[Id] UNIQUEIDENTIFIER NOT NULL, 
    [SiteId] UNIQUEIDENTIFIER NOT NULL, 
    [SelectedDate] DATETIME NULL, 
    [SolarLogValue] DECIMAL(20, 4) NULL, 
    [IsConfirm] BIT NULL, 
    [CreatedDateTime] DATETIME NULL, 
    [CreatedByUserId] UNIQUEIDENTIFIER NULL, 
    [UpdatedDateTime] DATETIME NULL, 
    [UpdatedByUserId] UNIQUEIDENTIFIER NULL, 
    [InActiveDateTime] DATETIME NULL, 
    [TimeStamp] TIMESTAMP NOT NULL 
CONSTRAINT [PK_SolarLogForm] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY], 
    [CompanyId] UNIQUEIDENTIFIER NOT NULL
) ON [PRIMARY]
GO
