CREATE TABLE [dbo].[TimeSheetPunchCard]
(
	[Id] UNIQUEIDENTIFIER NOT NULL, 
    [UserId] UNIQUEIDENTIFIER NOT NULL, 
    [Date] DATETIME NOT NULL, 
    [StartTime] DATETIME NULL, 
    [EndTime] DATETIME NULL, 
    [Breakmins] INT NULL, 
    [StatusId] UNIQUEIDENTIFIER NOT NULL, 
    [ApproverId] UNIQUEIDENTIFIER NULL ,
    [TimeSheetSubmissionId] UNIQUEIDENTIFIER NULL,
    [CreatedByUserId] UNIQUEIDENTIFIER NOT NULL, 
    [CreatedDateTime] DATETIME NOT NULL, 
	[CompanyId] UNIQUEIDENTIFIER NULL,
    [InActiveDateTime] DATETIME NULL, 
    [TimeStamp] TIMESTAMP NULL, 
    [UpdatedDateTime] DATETIME NULL, 
    [UpdatedByUserId] UNIQUEIDENTIFIER NULL, 
    [Summary]  NVARCHAR(MAX) NULL, 
    [RejectedReason] NVARCHAR(MAX) NULL, 
    [IsOnLeave] BIT NULL,
    [IsRejected] BIT NULL, 
    CONSTRAINT [PK_TimeSheetPunchCard] PRIMARY KEY ([Id]), 
    CONSTRAINT [FK_TimeSheetPunchCard_TimeSheetSubmission] FOREIGN KEY ([TimeSheetSubmissionId]) REFERENCES [TimeSheetSubmission]([id]), 
    CONSTRAINT [FK_TimeSheetPunchCard_Status] FOREIGN KEY ([StatusId]) REFERENCES [Status]([Id]), 
    CONSTRAINT [FK_TimeSheetPunchCard_User] FOREIGN KEY ([UserId]) REFERENCES [User]([Id]), 
    CONSTRAINT [FK_TimeSheetPunchCard_User_Approver] FOREIGN KEY ([ApproverId]) REFERENCES [User]([Id]), 
    CONSTRAINT [FK_TimeSheetPunchCard_Company] FOREIGN KEY ([CompanyId]) REFERENCES [Company]([Id]), 
   
)
