CREATE TABLE [dbo].[TVA]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	TVAValue DECIMAL(20, 4) NOT NULL,
	CompanyId UNIQUEIDENTIFIER NOT NULL,
	StartDate DATETIME NULL,
	EndDate DATETIME NULL,
	CreatedByUserId UNIQUEIDENTIFIER NOT NULL,
	CreatedDateTime DATETIME NOT NULL,
	UpdatedByUserId UNIQUEIDENTIFIER NULL,
	UpdatedDateTime DATETIME NULL,
	[InActiveDateTime] DATETIME NULL,
	[TimeStamp] TIMESTAMP
 CONSTRAINT [PK_TVA] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY], 
) ON [PRIMARY]
GO