CREATE TABLE [dbo].[UserLevel]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[UserId] UNIQUEIDENTIFIER NULL,
	[ProgramId] UNIQUEIDENTIFIER NULL,
	[LevelId] UNIQUEIDENTIFIER NULL,
	[CreatedDateTime] DATETIME NULL,
    [CreatedByUserId] UNIQUEIDENTIFIER NULL,
	[LevelName] NVARCHAR(50) NULL,
	[InactiveDateTime] DATETIME NULL
	 CONSTRAINT [PK_UserLevel] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
