//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace formioCommon.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public LangText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("formioCommon.Texts.LangText", typeof(LangText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data set id should not be empty.
        /// </summary>
        public static string DataSetIdNotFound {
            get {
                return ResourceManager.GetString("DataSetIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source with this name already exists.
        /// </summary>
        public static string DataSourceExist {
            get {
                return ResourceManager.GetString("DataSourceExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source id should not be empty.
        /// </summary>
        public static string DataSourceIdNotFound {
            get {
                return ResourceManager.GetString("DataSourceIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source type should not be empty.
        /// </summary>
        public static string DataSourceTypeNotFound {
            get {
                return ResourceManager.GetString("DataSourceTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create data set, Please contact administrator.
        /// </summary>
        public static string ExceptionCreateDataSet {
            get {
                return ResourceManager.GetString("ExceptionCreateDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create data source, Please contact administrator.
        /// </summary>
        public static string ExceptionCreateDataSource {
            get {
                return ResourceManager.GetString("ExceptionCreateDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create data source history.Please contact administrator.
        /// </summary>
        public static string ExceptionCreateDataSourceHistory {
            get {
                return ResourceManager.GetString("ExceptionCreateDataSourceHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create data source keys,Please contact administrator.
        /// </summary>
        public static string ExceptionCreateDataSourceKeys {
            get {
                return ResourceManager.GetString("ExceptionCreateDataSourceKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get data set by id, Please contact administrator.
        /// </summary>
        public static string ExceptionGetDataSetsById {
            get {
                return ResourceManager.GetString("ExceptionGetDataSetsById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to search data sets, Please contact administrator.
        /// </summary>
        public static string ExceptionSearchDataSets {
            get {
                return ResourceManager.GetString("ExceptionSearchDataSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to search data sources, Please contact administrator.
        /// </summary>
        public static string ExceptionSearchDataSource {
            get {
                return ResourceManager.GetString("ExceptionSearchDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to search data source history,Please cuntact administrator.
        /// </summary>
        public static string ExceptionSearchDataSourceHistory {
            get {
                return ResourceManager.GetString("ExceptionSearchDataSourceHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update data set, Please contact administrator.
        /// </summary>
        public static string ExceptionUpdateDataSet {
            get {
                return ResourceManager.GetString("ExceptionUpdateDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update data source, Please contact administrator.
        /// </summary>
        public static string ExceptionUpdateDataSource {
            get {
                return ResourceManager.GetString("ExceptionUpdateDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update data source keys, Please contact administrator.
        /// </summary>
        public static string ExceptionUpdateDataSourceKeys {
            get {
                return ResourceManager.GetString("ExceptionUpdateDataSourceKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide is Archived boolean.
        /// </summary>
        public static string IsArchivedShouldNotBeNull {
            get {
                return ResourceManager.GetString("IsArchivedShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key should not be empty.
        /// </summary>
        public static string KeyNotFound {
            get {
                return ResourceManager.GetString("KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name should not exceed 100 characters.
        /// </summary>
        public static string NameMaxLength {
            get {
                return ResourceManager.GetString("NameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name should not be empty.
        /// </summary>
        public static string NameNotFound {
            get {
                return ResourceManager.GetString("NameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companyid should not be empty.
        /// </summary>
        public static string NotEmptyCompanyId {
            get {
                return ResourceManager.GetString("NotEmptyCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in user should not be empty.
        /// </summary>
        public static string NotEmptyLoggedInUserId {
            get {
                return ResourceManager.GetString("NotEmptyLoggedInUserId", resourceCulture);
            }
        }

        //=====================================file exception==========================================
        public static string FileIdNotExists
        {
            get
            {
                return ResourceManager.GetString("FileIdNotExists", resourceCulture);
            }
        }
    }
}
