//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Btrak.Models.Assets
{
    public partial class AssetComment
    {
        public System.Guid Id { get; set; }
        public System.Guid AssetId { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.Guid CreatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public Nullable<System.Guid> UpdatedByUserId { get; set; }
    }
}
